### PR TITLE
LPS-142374 Unable to schedule Publications when using Safari and Firefox

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-142374

### CODE REVIEW

**Comment by stsquared99** [comment]
Testing considerations:
- Test with user timezone set to UTC, a plus, and a minus time zone (Making sure the offset works correctly)
- Schedule a few days ahead (basic, ensures all the js date conversions work)
- Reschedule
- Schedule jan 1, 1:01 the next year (makes sure all the padding works correct, eg 01/01/2022, 01:01)

**Comment by stsquared99** [comment]
As far as browsers, I think testing at least a reschedule on each browser? That is an important one, the loading in of a previous schedule date.

**Comment by xbrianlee** [comment]
Finished test analysis and manual testing with the use cases and browsers mentioned earlier. No issues discovered.

Discussed allowing the YYYY-M-D and YYYY-MM-DD format with Sam to keep parity with the other date pickers in Portal. Closing this PR for now.

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-publications/liferay-portal/pull/9

**Pull request closed without merging**
