### PR TITLE
LPD-33336 - Buffered increment runnable processing occurs in the same thread when not in production mode

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
@david-truong tested your changes and they looked good! 

I checked [this old regression ticket](https://liferay.atlassian.net/browse/LPS-117642), the issue I described in my [original PR](https://github.com/liferay-publications/liferay-portal/pull/1331#issuecomment-2276760814) where the User would be missing from the review changes screen, and the download speed while in a Publication. 

This was done with the following in my portal-ext.properties, to replicate the customer environment: 
```
buffered.increment.standby.queue.threshold=1000
buffered.increment.standby.time.upper.limit=60
```

Thanks for finding the right solution Dave!

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
