### PR TITLE
LPD-8381 LPD-15282 Send user notifications when publication fails to publish

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
Hi @pei-jung I was looking through the test results and noticed that the integration test causes a [PortalLogAssertor](https://testray.liferay.com/home/-/testray/case_results/2532061861?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2532061432%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failure since there are console failures. Since they are intentional, do you know if there is a way to ignore them in integration tests?

**Comment by pei-jung** [comment]
@brookedalton thanks for checking the failures. We need to capture the errors using `LogCapture`. I'll update the tests.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:report:2532380601

**Comment by pei-jung** [comment]
ci:forward:force

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:forward:force

**Comment by pei-jung** [comment]
ci:report:2532478637

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
Forwarded to BChan https://github.com/brianchandotcom/liferay-portal/pull/146776.

**Pull request closed without merging**
