### PR TITLE
LPS-201074 Create Test for TranslationEntry TableReferenceDefinition

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Manually forward to https://github.com/brianchandotcom/liferay-portal/pull/144184, the relevant failures are not related to current changes.

**Pull request closed without merging**
