### PR TITLE
[TS] LPS-162885 Take into account remote live sites in the query and the if statement

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Publications Team,

Can you help review this PR?

**Notes from @noornajj:**
> https://issues.liferay.com/browse/LPS-162885
> 
> The issue here is that it is possible to enable publications on remote live sites.
> To fix the issue, I updated the query that retrieves the staged groups to account for remote live sites. I also updated the if statement to include the hasRemoteStagingGroup() method.

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin can you add a test before we forward this one?

**Comment by suilin** [comment]
@david-truong sure, I will work on it.

**Comment by suilin** [comment]
@david-truong I resent the pull with the functional test on https://github.com/liferay-publications/liferay-portal/pull/274, but I found we cannot enable publications on remote live site, could you look at it? Thank you!

**Comment by david-truong** [comment]
That's perfect haha.  That's exactly what this ticket is fixing

**Comment by suilin** [comment]
@david-truong got it, now the added functioanl test passed on https://github.com/liferay-publications/liferay-portal/pull/274, can we forward https://github.com/liferay-publications/liferay-portal/pull/274?

**Comment by david-truong** [comment]
yes thanks!

**Comment by suilin** [comment]
Resent the pull with the functional test on https://github.com/liferay-publications/liferay-portal/pull/274.

**Pull request closed without merging**
