### PR TITLE
LPD-21520 Add workflow actions to the dropdown menu

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-21520](https://liferay.atlassian.net/browse/LPD-21520)

Add dropdown for assign
image

Assign to me popup
image
Assign to popup
image

Dropdown for actions and assign-to
image

Approve popup
image

Reject popup
image

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
See https://github.com/gislayne-vitorino/liferay-portal/pull/17.

**Pull request closed without merging**
