### PR TITLE
Lps 199053 2

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee is there issue fixed now?  can we forward this one?

**Comment by xbrianlee** [comment]
Something still doesn't seem quite right. I followed the steps in the bug ticket and tried to move the change but it seems to load indefinitely (no console or browser errors this time).
https://github.com/liferay-publications/liferay-portal/assets/7474820/baac26b2-ecd1-4aab-b513-51a556a4ed1d

I tested with the bundle from https://github.com/liferay-publications/liferay-portal/pull/782#issuecomment-1773618336.

**Comment by xbrianlee** [comment]
@noornajj Could you take another look?

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/liferay-publications/liferay-portal/pull/782

**Pull request closed without merging**
