### PR TITLE
LPS-157936 Create Upgrade to remove existing orphaned PortletPreferences

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-157936

This is a subtask of https://issues.liferay.com/browse/LPS-156786
- Original ticket PR: https://github.com/brianchandotcom/liferay-portal/pull/120031

@david-truong 
@xbrianlee if possible, could you please test this upgrade process against various environments using this data to upgrade from? It should be standard SQL, but just want to double check. If it isn't possible to use this data to test on CI I think what you can do is fine. I tested against MySQL 5.7 on my local: 
[PortletPref_Orphans_Testing.zip](https://github.com/liferay-publications/liferay-portal/files/9185560/PortletPref_Orphans_Testing.zip)

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
@ctang3 I'm seeing [several test failures on Oracle 19.3 and SQL Server 2017](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1917027114&testrayRunId=1917028491) that appear to be related to these changes. These upgrade failures happen when upgrading from both 7.3 and 7.4.

SQL Server ([console log](https://testray.liferay.com/reports/production/logs/2022-07/test-1-30/test-portal-acceptance-pullrequest(master)/3904/functional-upgrade-tomcat90-sqlserver2017-jdk8/0/2/jenkins-console.txt.gz?authuser=0), [7.4.13-data-archive-publications-sqlserver.zip](https://github.com/liferay-publications/liferay-portal/files/9192196/7.4.13-data-archive-publications-sqlserver.zip)):
```
     [java] 2022-07-26 05:41:37.971 ERROR [Portal Dependency Manager Component Executor--1][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'false'.
```
Oracle ([console log](https://testray.liferay.com/reports/production/logs/2022-07/test-1-30/test-portal-acceptance-pullrequest(master)/3904/functional-upgrade-tomcat90-oracle193-jdk8/0/0/jenkins-console.txt.gz?authuser=0), [7.3.10-data-archive-publications-oracle.zip](https://github.com/liferay-publications/liferay-portal/files/9192198/7.3.10-data-archive-publications-oracle.zip)
):
```
     [java] 2022-07-26 05:49:18.050 ERROR [Portal Dependency Manager Component Executor--1][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: ORA-00904: "FALSE": invalid identifier
```

These are the steps used to create the database dumps linked above: [LRQA-64715](https://issues.liferay.com/browse/LRQA-64715)

**Comment by xbrianlee** [comment]
@ctang3 Also I can work on automating the upgrade for the database dump you linked above if you send me the steps to create the database dump and what we should verify after upgrading

**Comment by noraszel** [comment]
New JIRA ticket for this is we continue: https://issues.liferay.com/browse/LPS-162882

**Pull request closed without merging**
