### PR TITLE
LPS-180098 Index CTEntry Table

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @xbrianlee, are the failures related?

**Comment by xbrianlee** [comment]
@pei-jung The test failure from `relevant` is related to these changes: [com.liferay.change.tracking.internal.search.test.SearchCTTest](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521231/testReport/com.liferay.change.tracking.internal.search.test/SearchCTTest)
```
##
## com.liferay.change.tracking.internal.search.test.SearchCTTest > testPublishAndUndoLayout
##

	org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"filter":[{"bool":{"must":[{"bool":{"must":[{"terms":{"groupId":["58856"]}},{"terms":{"scopeGroupId":["58856"]}}]}},{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.portal.kernel.model.Layout"}}},{"terms":{"type":["portlet"]}},{"terms":{"status":["0"]}},{"terms":{"type":["portlet"]}},{"terms":{"status":["0"]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":["uid","companyId","entryClassPK","entryClassName","scopeGroupId","groupId","modified","defaultLanguageId","title_en_US","title","content","content_en_US"],"track_scores":true,"track_total_hits":2147483647}->{uid=com.liferay.portal.kernel.model.Layout_PORTLET_49, entryClassPK=49, companyId=20096, entryClassName=com.liferay.portal.kernel.model.Layout, scopeGroupId=58856, groupId=58856, modified=20230516200654, defaultLanguageId=en_US, title_en_US=45qJkAkF},{uid=com.liferay.portal.kernel.model.Layout_PORTLET_50, entryClassPK=50, companyId=20096, entryClassName=com.liferay.portal.kernel.model.Layout, scopeGroupId=58856, groupId=58856, modified=20230516200654, defaultLanguageId=en_US, title_en_US=7bS51LV4}->[com.liferay.portal.kernel.model.Layout_PORTLET_49, com.liferay.portal.kernel.model.Layout_PORTLET_50] expected:<...del.Layout_PORTLET_4[8, com.liferay.portal.kernel.model.Layout_PORTLET_4]9, com.liferay.porta...> but was:<...del.Layout_PORTLET_4[]9, com.liferay.porta...>
```

Would you like me to run additional test suites at this time? We should regression test AS and DB functionality since many CT modules are being changed.

**Comment by pei-jung** [comment]
Thanks @xbrianlee. I'll look into the `SearchCTTest` failure. 

What are the commands for the other test suites? I'll run them after I fix the test failure.

**Comment by xbrianlee** [comment]
Thanks! The other test suites are `publications`, `publications-as`, and `publications-db`. I analyze the test results when they're finished.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:publications-as

**Comment by pei-jung** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
@xbrianlee is this PR good?

**Comment by xbrianlee** [comment]
ci:test:publications-db

Re-running this test suite since there are some unique failures that didn't pass in the upstream run from today

**Comment by xbrianlee** [comment]
`publications` and `publications-as` results look good

**Comment by xbrianlee** [comment]
@pei-jung There seems to be a DB2 test failure that has failed multiple times on this PR but isn't happening upstream. The test does the following and then runs into an error:
1. Add a folder via JSON
```curl -X POST -u 'test@liferay.com:test' -d 'externalReferenceCode=' -d 'repositoryId=50172' -d 'parentFolderId=0' -d 'name=DM Folder 1 Name' -d 'description=DM Folder 1 Description' -d 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-folder```
2. Add a Publication via JSON
```curl -X POST -u 'test@liferay.com:test' -d 'companyId=47686' -d 'userId=47718' -d 'name=Publication+Name' -d 'description=' http://localhost:8080/api/jsonws/ct.ctcollection/add-ct-collection```
3. Select Publication via JSON
```curl -X POST -u 'test@liferay.com:test' -d 'companyId=47686' -d 'ctCollectionId=2' -d 'userId=47718' http://test-1-40-75.lax.liferay.com:8080/api/jsonws/ct.ctpreferences/checkout-ct-collection```

Errors:
```
[beanshell] 2023-05-23 01:31:25.899 ERROR [http-nio-8080-exec-2][BatchingBatch:134] HHH000315: Exception executing batch [com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][4.24.92] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
[beanshell] Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null], SQL: insert into DLFolder (mvccVersion, ctCollectionId, uuid_, externalReferenceCode, groupId, companyId, userId, userName, createDate, modifiedDate, repositoryId, mountPoint, parentFolderId, treePath, name, description, lastPostDate, defaultFileEntryTypeId, hidden_, restrictionType, lastPublishDate, status, statusByUserId, statusByUserName, statusDate, folderId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[beanshell] 2023-05-23 01:31:25.916 ERROR [http-nio-8080-exec-2][SqlExceptionHelper:142] [jcc][t4][102][10040][4.24.92] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
[beanshell] Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
[beanshell] 2023-05-23 01:31:25.917 ERROR [http-nio-8080-exec-2][SqlExceptionHelper:142] Error for batch element #1: DB2 SQL Error: SQLCODE=-803, SQLSTATE=23505, SQLERRMC=11;ROOT.DLFOLDER, DRIVER=4.24.92
[beanshell] 2023-05-23 01:31:25.926 ERROR [http-nio-8080-exec-2][JSONWebServiceServiceAction:126] could not execute batch; SQL [insert into DLFolder (mvccVersion, ctCollectionId, uuid_, externalReferenceCode, groupId, companyId, userId, userName, createDate, modifiedDate, repositoryId, mountPoint, parentFolderId, treePath, name, description, lastPostDate, defaultFileEntryTypeId, hidden_, restrictionType, lastPublishDate, status, statusByUserId, statusByUserName, statusDate, folderId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
     [exec]     LIFERAY_ERROR: HHH000315: Exception executing batch [com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][4.24.92] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
     [exec]     Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null], SQL: insert into DLFolder (mvccVersion, ctCollectionId, uuid_, externalReferenceCode, groupId, companyId, userId, userName, createDate, modifiedDate, repositoryId, mountPoint, parentFolderId, treePath, name, description, lastPostDate, defaultFileEntryTypeId, hidden_, restrictionType, lastPublishDate, status, statusByUserId, statusByUserName, statusDate, folderId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     [exec]     LIFERAY_ERROR: [jcc][t4][102][10040][4.24.92] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
     [exec]     Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
     [exec]     LIFERAY_ERROR: Error for batch element #1: DB2 SQL Error: SQLCODE=-803, SQLSTATE=23505, SQLERRMC=11;ROOT.DLFOLDER, DRIVER=4.24.92
     [exec]     LIFERAY_ERROR: could not execute batch; SQL [insert into DLFolder (mvccVersion, ctCollectionId, uuid_, externalReferenceCode, groupId, companyId, userId, userName, createDate, modifiedDate, repositoryId, mountPoint, parentFolderId, treePath, name, description, lastPostDate, defaultFileEntryTypeId, hidden_, restrictionType, lastPublishDate, status, statusByUserId, statusByUserName, statusDate, folderId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
```
Links: [Testray](https://testray.liferay.com/home/-/testray/case_results/2316037789)(Poshi report isn't helpful since test passes in the subsequent run), [Full console log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-28/test-portal-acceptance-pullrequest(master)/6507/functional-tomcat90-db2111-jdk8/1/1/jenkins-console.txt.gz?authuser=0)

From the stacktrace, does it seem obvious what the issue could be? If not, I can investigate this further.

**Comment by pei-jung** [comment]
@xbrianlee I fixed the rebase conflict and force pushed.

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
