### PR TITLE
LPD-24645 Do not show workflow tab for drafts of entities

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-24645

### CODE REVIEW

**Comment by brookedalton** [comment]
SF failed for unrelated playwright test
 ```tests/frontend-data-set-views-web/pages/view/tabs/ActionsPage.ts: BAD
     [exec] Prettier checked 445 files, 1 file has problems

**Comment by brookedalton** [comment]
https://github.com/liferay-publications/liferay-portal/assets/46908843/7ed7042d-0177-4284-8a4b-d9d12067c317

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
Hi @noornajj, BChan closed the first pull request and although this fix is the same, I made it a little more clear that the workflowStatus Int obj is actually comparing the number value. Let me know if I should change anything, thanks!

**Comment by noornajj** [comment]
Hi @brookedalton 
Well, based on the link that BChan sent you, your old code should work since the operation you are doing is: (Integer) != int
This will unbox the (Integer) object into and int and the operation should work
I don't see a need to change anything. Maybe you can message him through slack and explain your code works?

**Comment by brookedalton** [comment]
😭

**Pull request closed without merging**
