### PR TITLE
LPS-156136 Avoid redundant fetchLayout call as Layout#isPublished will also check existence of the draft layout. This cuts half of the fetchLayout calls on a content page when CT is enabled.

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is one thing that I found today. I haven't tested it myself, but from profile it should cut half of the fetchLayout calls from NavItem, which contributes the most major part of these calls.

### CODE REVIEW

**Comment by tinatian** [comment]
@ealonso I believe your code won't save as much fetching as Dante's. I am wondering if there is anything wrong with Dante's code. 

Tina.

**Comment by ealonso** [comment]
Hey @tinatian,

Having 10 Content Pages, we have 10 Published pages + 10 Draft pages, it is 20 pages.

Taking into account the isPublished method:
```java
public boolean isPublished() {
	if (!isTypeContent()) {
		return true;
	}

	Layout draftLayout = fetchDraftLayout();

	if ((draftLayout == null) ||
		GetterUtil.getBoolean(
			draftLayout.getTypeSettingsProperty("published"))) {

		return true;
	}

	return false;
}
```

With master code:

```java
if (layout.fetchDraftLayout() != null) {
	return !layout.isPublished();
}
``` 
We are executing the first fetch for 20 pages and then the isPublished method that have a fetch for 10 pages (it is only for published pages, since draft pages doesn't have a draft page).

With @dantewang code:

```java
if (layout.isPublished()) {
	return false;
}
``` 
We are executing the isPublished method that have a fetch for 20 pages.

With my code:

```java
if (layout.isDraftLayout()) {
	return true;
}

Layout draftLayout = LayoutLocalServiceUtil.fetchLayout(
	PortalUtil.getClassNameId(Layout.class), layout.getPlid());
```
With the first line we are excluding all draft pages then we are executing the fetch only for 10 pages. The is draft method check the className and classPk to exclude pages, so, no fetch are executed.

Hope it's helps, but maybe I'm doing something wrong.

Please let me know if you need to talk about it.

**Comment by dantewang** [comment]
@ealonso With master code:

```
if (layout.fetchDraftLayout() != null) {
	return !layout.isPublished();
}
```

By reading the profile, I see exactly same numbers (1430 vs 1430) of layout fetch from `layout.fetchDraftLayout()` and `layout.isPublished()` when visiting the "110 tabs page" (see the attached database dump in the ticket).

I only started profile, hit that page, and captured the snapshot. So all these invocations are from the page rendering.

**Comment by tinatian** [comment]
@ealonso What Dante means, when recording all the invocations happens at runtime, "layout.fetchDraftLayout()" is never null, and it will always invoke "!layout.isPublished()". So what his fixes is to invoke "!layout.isPublished()" directly to avoid this fetching "layout.fetchDraftLayout()".

We have this fix based on the profiles by recording runtime invocations, but we are not sure if this makes sense from code level.

So we have finished this round of performance tuning, and we do not need this fix if you think this is risk.

I am going to close this pull.

Thanks.
Tina.

**Pull request closed without merging**
