### PR TITLE
LPS-198153 Pass missing data to ChangeTrackingRenderView

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPS-198153

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
@ctang3 needs to look further into namespace

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by brianchandotcom** [comment]
@noornajj @xbrianlee I merged this manually.

**Pull request closed without merging**
