### PR TITLE
LPD-17055 Block object deletion if it's being modified in publications

### PR DESCRIPTION
**Pull request by pei-jung**
Error message when deletion is blocked
Screen Shot 2024-02-08 at 8 08 37 PM

Conflict message and only the **_discard_** action is available for this conflict
Screen Shot 2024-02-08 at 1 45 08 PM

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:report:2537997616

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:report:2538586947

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
Force-pushed the branch to fix a semantic version failure. Other failures look unrelated. I'll retrigger the tests to confirm. 

@david-truong can you review my changes when you get a chance? Thanks!

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:report:2539013622

**Comment by david-truong** [comment]
looks good to me

**Comment by pei-jung** [comment]
ci:forward:force

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
