### PR TITLE
LPS-198225 Create test for DDMStructureLayoutTableReferenceDefinition

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-198225](https://liferay.atlassian.net/browse/LPS-198225)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
