### PR TITLE
LPS-184475 - org.hibernate.StaleObjectStateException related to LayoutImpl

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:echo

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
@xbrianlee i sent just the first commit

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
