### PR TITLE
LPS-133974 | Add tests for StyleBookEntry TableReferenceDefinition

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-133974

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@xbrianlee are the failures related?

**Comment by xbrianlee** [comment]
Failures are unrelated. Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/142217.

**Pull request closed without merging**
