### PR TITLE
LPS-198236 - Create test for DDMStorageLinkTableReferenceDefinition

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
