### PR TITLE
LPS-159649, LPS-160960 Workflow UI & Test Fixes

### PR DESCRIPTION
**Pull request by xbrianlee**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:publications-environments:norebase

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/250

**Pull request closed without merging**
