### PR TITLE
LPS-174929 - Publications with LAR import is not mergeable into Production

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:reevaluate:1317401_7045

**Comment by david-truong** [comment]
ci:reevaluate:1317401_7045

**Comment by david-truong** [comment]
ci:reevaluate:1317401_7045

**Comment by david-truong** [comment]
@xbrianlee can you help me check the results of this one?

**Comment by xbrianlee** [comment]
@david-truong Test failures for `publications` and `relevant` are all unrelated to this PR

**Comment by david-truong** [comment]
Please forward

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
