### PR TITLE
LPS-164752 - As a publication user, I would like to use knowledge base with publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:stop

**Comment by Vy-CES** [comment]
Hi @david-truong, is there any pending action from my side on this issue?

**Comment by david-truong** [comment]
no it is already merged: https://github.com/liferay-publications/liferay-portal/pull/460

**Comment by david-truong** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/131583

**Pull request closed without merging**
