### PR TITLE
LPS-161315 - As a publication admin, I would like to define templates that users can use to create their publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee can you add any test fixes needed to this branch?

**Comment by suilin** [comment]
@david-truong, there are two regression bugs in this PR, could you look at it? Thank you!
1. Error message {{Error:Unexpected token '<', }} displays when adding publication without name or with a long name, this error is same on https://github.com/liferay-publications/liferay-portal/pull/316, here is the [console log](https://gist.github.com/suilin/f395d9f12d07a93c72f840fd521da9fc).
2. Test test user didn't invite themselves by default when adding a new publications with JSON, it doesn't happen when adding publication by manually, the issue seems to be caused by [this commit](https://github.com/liferay-publications/liferay-portal/pull/340/commits/1a9feaef043af9c5dd1bd18d012c91843df64834)

And I sent the pr with test-fixes on https://github.com/liferay-publications/liferay-portal/pull/341

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee @suilin can we open a new bug ticket for #2.  Let's try to get it merged as is if the test results look okay

**Comment by david-truong** [comment]
@xbrianlee that seems like a lot of failures

**Comment by suilin** [comment]
@david-truong, I analyzed the Publications suite test results and found that we cannot create Publications on the page, after clicking on create button, it navigates to a blank page, same behavior for reverting a publication. The issue causes lots of tests failed and the two regressions also cann't verify due to be blocked by the issue, could you take a look at it? Thank  you!

**Comment by suilin** [comment]
> @xbrianlee @suilin can we open a new bug ticket for #2. Let's try to get it merged as is if the test results look okay

@david-truong, I'm a little confused about #2, do you mean create a new bug ticket for the existing ticket [LPS-146644](https://issues.liferay.com/browse/LPS-146644)?

**Comment by ctang3** [comment]
@suilin I think he means this issue:

> The user cannot be invited when inviting user through the publication Ellipsis dropdown menu > Invite Users even the sucess message displays, but it works when inviting user through tbar in Review Page.

**Comment by suilin** [comment]
@ctang3, thanks for your confimation, I will create the ticket. Do we need to re-trigger Publications test suite to look at the results after the new changes?

**Comment by ctang3** [comment]
@suilin yesm please do. This issue should be fixed: 
>Error message {{Error:Unexpected token '<', }} displays when adding publication without name or with a long name, this error is same on https://github.com/liferay-publications/liferay-portal/pull/316, here is the [console log](https://gist.github.com/suilin/f395d9f12d07a93c72f840fd521da9fc).

**Comment by suilin** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by suilin** [comment]
@david-truong @ctang3,

> 1. Error message {{Error:Unexpected token '<', }} displays when adding publication without name or with a long name, this error is same on https://github.com/liferay-publications/liferay-portal/pull/316, here is the [console log](https://gist.github.com/suilin/f395d9f12d07a93c72f840fd521da9fc).
> 2. The user cannot be invited when inviting user through the publication Ellipsis dropdown menu > Invite Users even the sucess message displays, but it works when inviting user through tbar in Review Page.

- The first issue has been resolved, the Create button is grey that cann't create instead of alert message displays, it that the expected result? If it is I will update our tests based on the behavior.
- The second issue still can be reproduced, and it's caused by the current changes, will we fix it in the PR? Thank you!

**Comment by david-truong** [comment]
1. @suilin that is the new behavior that @ctang3 changed it to
2. Can we create a new bug ticket for it.  We will fix it after this gets merged.  Since there is a workaround I would like to move forward with the current changes as is.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
Hi @david-truong and @ctang3, could you look at the first issue? Thank you!
> Error message {{Error:Unexpected token '<', }} displays when adding publication without name or with a long name, this error is same on https://github.com/liferay-publications/liferay-portal/pull/316, here is the [console log](https://gist.github.com/suilin/f395d9f12d07a93c72f840fd521da9fc).
> The user cannot be invited when inviting user through the publication Ellipsis dropdown menu > Invite Users even the sucess message displays, but it works when inviting user through tbar in Review Page.

* I found the the first issue Error message {{Error:Unexpected token '<', }}, it's fixed on when creating publication without name or with a long name, but it still can be reproduced when editing the publication. (The issue didn't find due to it was blocked by the second issue in the pr result.)
* The second issue I filed the ticket [LPS-170879](https://issues.liferay.com/browse/LPS-170879), to workaround it I updated the tests to invite users through review changes page, I sent to https://github.com/liferay-publications/liferay-portal/pull/344

**Comment by xbrianlee** [comment]
Discovered some more bugs within the Create Publications Template page:
- Setting the Publications Name field to something long (e.g. `Pub - ${TEMPLATE_CREATOR} ${TODAY_DATE} ${RANDOM_NUMBER} ${CURRENT_USERNAME}`) causes the following form feedback message to show up: Value exceeds maximum length of {0}. However the Publications Template can still be created.
- Set Publications Template Name field to `PT1`, set Publication Name field to Pub ${RANDOM_NUMBER}, and save. Look at PT1 again and note that Publication Name field didn't save properly.
- Unable to invite users to collaborate on a Publications Template.
- Publications Collaborators help text icon doesn't show any help text.

Tested with the bundle in https://github.com/liferay-publications/liferay-portal/pull/340#issuecomment-1344135851.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin i fixed the editing CTCollection issue.

**Comment by suilin** [comment]
ci:test:publications

**Comment by david-truong** [comment]
No the issues you brought up need to be fixed. @ctang3 has started on them

**Comment by suilin** [comment]
@david-truong, there is still a potentiall test fix issue, could you cherry-pick [this commit](https://github.com/liferay-publications/liferay-portal/pull/344/commits/122b015c35a08987fac49fd399667d75d01aa37b) to this branch? Thank you!

**Comment by david-truong** [comment]
@suilin @ctang3 added your fixes.

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@suilin can you retest all the issues with this latest build. If it passes please forward.

**Pull request closed without merging**
