### PR TITLE
Lps 178009 updated

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@noornajj can you rebase and try again?  Seems like you are on a bad commit with SF issues

**Comment by noornajj** [comment]
ci:test:sf

**Comment by david-truong** [comment]
rebased: https://github.com/liferay-publications/liferay-portal/pull/701

**Pull request closed without merging**
