### PR TITLE
LPS-148530 fix duplicate search results

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@xbrianlee are the failures normal?

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@tinatian updated the pr with the changes you requested

**Comment by david-truong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-publications/liferay-portal/pull/99

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
