### PR TITLE
LPS-133980 | Create Tests for Workflow TableReferenceDefinitions

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-133980

### CODE REVIEW

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
