### PR TITLE
LPS-178710 Move changes error alert doesn't show up consistently

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-178710
@david-truong

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee @ctang3 can you work together to update the tests to the new expected results?

**Comment by xbrianlee** [comment]
@suilin Can you work on these test fixes on Monday if you have time? I won't be able to get around to this today.

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @ctang3, I'm working on updating the test-fixes for the new change, but I find we cannot move changes even though there are no conflict changes, here are the steps, could you help to look at it?

- Enable Publications
- Add a new web content article
- Add a new publication "P1"
- Add a new publication "P2"
- In "P2", edit the new web content article
- Review changes for "P2" and select the changes
- Move changes and select "P1"
- "The changes could not be moved." the alert message shows up
Failure

For another test it's a test-fix issue, I updated the test based on the new changes, and I sent it on https://github.com/liferay-publications/liferay-portal/pull/503

cc @david-truong @xbrianlee

**Comment by Kokuyo3** [comment]
@suilin Hi Linda, I'll take a look. With the steps you commented, you should still be able to move changes so it is a valid issue. 

However, in case it affects the test updating - I did notice that the test steps in this ticket ([LPS-178710](https://issues.liferay.com/browse/LPS-178710)) is different from the linked "discovered while testing" ticket,([LPS-177237](https://issues.liferay.com/browse/LPS-177237)). It is missing a step to edit the article in P1. The original (LPS-177237) seems to test for a conflict. 

cc @david-truong @xbrianlee

**Comment by ctang3** [comment]
@suilin Just pushed a fix, so the issue you found should be corrected now. Thanks!

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @ctang3, I have checked it, the issue that I mentioned above has been resolved, and I cherry-pick your commit and my test-fixes commit into https://github.com/liferay-publications/liferay-portal/pull/503, everything looks fine, do you think we can forward https://github.com/liferay-publications/liferay-portal/pull/503?

cc @david-truong @xbrianlee

**Pull request closed without merging**
