### PR TITLE
LPD-24645 Do not show workflow tab for drafts of entities

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-24645

### CODE REVIEW

**Comment by pei-jung** [comment]
@noornajj can you help review this PR? Thanks!

**Comment by noornajj** [comment]
@brookedalton The changes look good to me. Just a comment on the playwright test, couldn't you have just used journalPagesTest to test the draft entity since we already have that included? Just to avoid including more imports than necessary.

cc @pei-jung

**Comment by brookedalton** [comment]
Hey @noornajj, I was having trouble saving the web content as a draft since there is no success message when saving a WC as a draft and the playwright test would go to review changes really fast before the draft was created. I can try to wait for another type of signal or try to re-navigate to the web content admin to assert it is there if you think that is better?

**Comment by noornajj** [comment]
Hi @brookedalton 
Thanks for updating the test. Everything looks good to me.

cc @pei-jung

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
