### PR TITLE
LPS-197750 CTDisplayRenderer back url fixes

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPS-197750

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Review by pei-jung — CHANGES_REQUESTED** [review]
@ctang3 The back button is still not clickable for UserGroup and Role. Both portlets use the `backURL` for the back button. Let's use the current url as the default for `backURL`.

**Comment by ctang3** [comment]
@pei-jung Hmm I do see the back button working on my side for UserGroup and Role. Could you have missed the commits for those when pulling my branch? 

I noticed that for some entities, the httpServletRequest in its CTDisplayRenderer doesn't have a `backURL` param. But the [entity's .jsp edit page defaults to using the `redirect` param](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/edit_user_group.jsp#L13) as a default if no `backURL` is provided, so that is why I just removed the setBackURL from the CTDisplayRenderers

image

^ Hovering over the back button, the link preview shows at the bottom.

**Comment by pei-jung** [comment]
@ctang3 ah ok. I missed the part that the backURL is using the redirect as its default. This changes look good. Thank you!

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
