### PR TITLE
LPS-142514 - Comments sidebar styles

### PR DESCRIPTION
**Pull request by victorcdp**

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:stop

**Comment by victorcdp** [comment]
ci:test:publications
ci:test:relevant

**Comment by brunofalc** [comment]
Hey @xbrianlee could you take a look at this?

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward

Test results above look good.

**Pull request closed without merging**
