### PR TITLE
LPS-199203 - Content page is not support locales in review changes

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@suilin are the results okay?

**Comment by suilin** [comment]
@david-truong, after the changes both the widget and content page preview src are changed when viewing the page details, are they the expected result?

Example for widget preview:
Before: the preview url is `src="http://localhost:8080/web/site-name/test-page?p_l_mode=preview&previewCTCollectionId=1"`
Now: it's `src="/c/portal/update_language?p_l_id=20&languageId=en_US&persistState=false&showUserLocaleOptionsMessage=false&redirect=http%3A%2F%2Flocalhost%3A8080%2Fweb%2Fguest%2Ftest-page%3Fp_l_mode%3Dpreview%26previewCTCollectionId%3D0%26segmentsExperienceId%3D32673"`

If it's the expected result, I will update the tests to match.

**Comment by david-truong** [comment]
@suilin yes the redirect should more or less match the old url.  the new url allows us to change the locale properly without it saving for the user

**Comment by suilin** [comment]
@david-truong, thanks for your confirmation and we will send the PR with test fixes on [LPS-201912](https://liferay.atlassian.net/browse/LPS-201912).

**Comment by suilin** [comment]
Hi @david-truong, this pr has a conflict issue and failed to rebase, can you look at it? Thanks

**Comment by suilin** [comment]
Hi @david-truong, in case you missed my previous message, can you help to rebase it since it has a conflict when rebased master?Thanks.

**Comment by pei-jung** [comment]
@suilin I didn't run into any conflicts when rebasing onto master. Dave is on PTO this week. Here is the updated PR: https://github.com/liferay-publications/liferay-portal/pull/863

**Pull request closed without merging**
