### PR TITLE
LPS-178009 - As a publication user, I would like to know all the changes that will be moved, when I move changes.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee we can't get sf to pass.  the errors are not files we modified

**Comment by xbrianlee** [comment]
@david-truong SF will be fixed by https://github.com/ling-alan-huang/liferay-portal/pull/2145. We'll have to manually forward this if the other forward checks pass.

**Comment by david-truong** [comment]
@xbrianlee can you check the results and forward if they are okay

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@david-truong There's a compile error for `change-tracking-test`. Could you take a look?
https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8219/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Comment by xbrianlee** [comment]
The publications results look good. Just waiting on a fix for the issue I described above before forwarding.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee i fixed the compile error.  can we forward?

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
