### PR TITLE
LPS-154710 As a publication user, I would like to enable publications through an osgi configuration

### PR DESCRIPTION
**Pull request by xbrianlee**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by david-truong** [comment]
rebased and resent: https://github.com/liferay-publications/liferay-portal/pull/110

**Pull request closed without merging**
