### PR TITLE
LPS-196957 | Enable change tracking for country and region

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-196957

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Review by pei-jung — APPROVED** [review]

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@xbrianlee can you forward this if the tests look good?

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
