### PR TITLE
LPD-25058 Add button to view more workflow activity results

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-25058

### CODE REVIEW

**Comment by brookedalton** [comment]
https://github.com/liferay-publications/liferay-portal/assets/46908843/c57dd9a4-2ace-42cc-8fe7-7601199c0131

**Review by pei-jung — APPROVED** [review]
Well done! 👍

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
