### PR TITLE
LPD-20756, LPD-20820 - Generate pages and webcontent data

### PR DESCRIPTION
**Pull request by ctang3**
Continuation of https://github.com/liferay-publications/liferay-portal/pull/1167

Combining these into a single PR since LPD-20820 depends on LPD-20756. Also attached is the generated data dump in MySQL format and my modified SampleSQLBuilderTest.java for easier local testing and data generation.

The publications group and site are on liferay1.com and liferay2.com virtual hosts.

- https://liferay.atlassian.net/browse/LPD-20756
- https://liferay.atlassian.net/browse/LPD-20820

📁 [mysql_dump.zip](https://github.com/user-attachments/files/15842580/mysql_dump.zip)
📁 [modified_SampleSQLBuilderTest.zip](https://github.com/user-attachments/files/15842597/modified_SampleSQLBuilderTest.zip)

### CODE REVIEW

**Comment by ctang3** [comment]
Fixing errors caused by upstream changes after rebasing.

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@dantewang can you take a look at this to see if we create the data correctly?

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
