### PR TITLE
LPS-201585 - Allow CT Entities to be cacheable

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications:norebase

**Comment by david-truong** [comment]
ci:test:relevant:norebase

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by tinatian** [comment]
@GinsonRen Please run Login performance tests on this pull. One with the customized properties we did for benchmark and one without all the changes we made recently.

Thanks.
Tina.

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Pull request closed without merging**
