### PR TITLE
LPS-187437 Create a user that can be associated to a CTCollection

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @xbrianlee, are the failures related?

**Comment by xbrianlee** [comment]
ci:test:relevant

Publications suite looks good, but there are some unique failures in relevant. Re-running this suite to see if they are flukes.

**Comment by xbrianlee** [comment]
@pei-jung These test failures are related to these changes. Could you please take a look at them?
- [com.liferay.roles.admin.internal.exportimport.data.handler.test.RolesAdminPortletDataHandlerTest](https://testray.liferay.com/home/-/testray/case_results/2411953869)
- [com.liferay.roles.service.test.RoleLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/2411953933)

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@xbrianlee looks like some of the test builds were aborted. Should I re-trigger the relevant test?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
