### PR TITLE
LPS-161315 Publication Templates

### PR DESCRIPTION
**Pull request by ctang3**
Commits squashed from https://github.com/liferay/liferay-portal/compare/master...ctang3:liferay-portal:LPS-161315_Publication_Templates. 

JSON Storage seems straight forward to use, so I kept with using it for the storing/getting the templated publication name and user info.

There is a blocker with testing a publication revert - there's an error when attempting to submit a revert that I'm guessing stems from something to do with the option to publish now vs later. However, I don't see code related to the now vs later scheduling when I look through the edit_ct_collection.jsp and EditCTCollectionMVCAction class so I'm confused on the source of this error.

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 

1. can you squash the [d9ebd10](https://github.com/liferay-publications/liferay-portal/pull/316/commits/d9ebd1039108f806f0c3ca83ed5b95636bb9813b) and [a4b498e](https://github.com/liferay-publications/liferay-portal/pull/316/commits/a4b498e2da1db767f899b31615d145da3cd631a8) together to prevent the additional change in packageinfo?
2. Can you also allow the invite collaborators to support inviting yourself in a template?
3. Can you add some space between Create and Cancel in the Create New Publication screen?
4. Did we add support for tokens in templates publication name and publication descriptions?

**Comment by ctang3** [comment]
> * can you squash the [d9ebd10](https://github.com/liferay-publications/liferay-portal/pull/316/commits/d9ebd1039108f806f0c3ca83ed5b95636bb9813b) and [a4b498e](https://github.com/liferay-publications/liferay-portal/pull/316/commits/a4b498e2da1db767f899b31615d145da3cd631a8) together to prevent the additional change in packageinfo?
> * Can you also allow the invite collaborators to support inviting yourself in a template?
> * Can you add some space between Create and Cancel in the Create New Publication screen?
> * Did we add support for tokens in templates publication name and publication descriptions?


@david-truong As an update on this: I pushed code to address 1, 3, 4. Currently working on the collaborator inviting part.

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
Hi @xbrianlee & @suilin, this PR is pretty much complete. Could we have tests written for it? It's a pretty large PR but I'll try to summarize the changes and happy path some test steps: 

**TICKET:** https://issues.liferay.com/browse/LPS-161313

**SUMMARY:** 
This PR adds a new feature - the ability to create Publication Templates, which can be used to quickly create new Publications and reduce repetitive work. 
- A template has its own name and description in addition to a "preset" name and description for Publications created from it. 
  - The preset Publication name and description can use string tokens such as `${TODAY_DATE}` to dynamically generate strings when the template is being used to create a publication, allowing some degree of uniqueness when creating multiple Publications from the same Template. 
  - `${TEMPLATE_CREATOR}'s Publication - ${RANDOM_NUMBER}` would parse into something like `Cheryl's Publication - 23812346`
  - Template string tokens' values are generated by the backend when the "Publication Creation" page loads
- When creating a Template, one can select Users that will be automatically invite to to Publications created from it. 
- A dropdown for selecting which Template to use as the base has been added to the Publication creation page
  - Upon selecting a Template from the dropdown, the Publication's name and description should be autofilled
- The "Create/Edit Publication" Page was rewritten to use React, so some locators may now be broken

**NEW PAGES/ELEMENTS:**

- A new "View Templates" page displaying a table of created Templates
  - Accessed from the View Publications page > vertical ellipses in the top right > Templates
- A new page for creating a Template
  - View Templates page > blue + button
  - The "Publication Information" collapsible panel contains a tooltip/alert listing the available string tokens 
  - The modal for inviting users to a template is the same code (with a couple tweaks) as the one for inviting users to collaborate on a Publication, so locators should be reusable
    - The current user is not automatically shown/added in the modal, so that a user can add themselves to a template. This is only for the Template Creation page's modal - the modal for inviting users to a Publication should be the same as before
- A drop down selector of Templates is added at the top of the "Create Publication" page's form

**HAPPY PATH STEPS:**

1. Create a couple new Users
2. Enable Publications
3. Go to the Template Creation page (View Publications page > vertical ellipses in the top right > click Templates in drop down > click blue + button)
4. Enter names/description for the Template
5. Expand "Publication Information" collapsible panel
6. Enter Publication name and description. Test using a string token for both fields.
7. Click the 'Invite Users' button and select User(s) that will be automatically invited to Publications created from this Template
8. Click Create button
9. You should be redirected to the "View Templates" page. The newly created template should be in the table. 
10. Go to the "Publication Creation" page
11. Select a Template from the drop down
12. The Publication's name/description should be autofilled
13. Selecting a different Template should update the autofilled fields accordingly 
14. String template tokens should be replaced with dynamically generated text values
15. Create the Publication
16. Users added to the Template should automatically be invited to the new Publication

**AREAS OF CONCERN FOR TESTING :**

- Template users should be automatically invited to Publications as expected
- A User should be able to add themselves to the invite list when creating a Template. They should not already be in the modal's table. 
- If a User invites others but doesn't invite themselves when creating a template, they shouldn't be able to see Publications created from that template (@david-truong please confirm if this should be the case)
- Auto-invited Users' permissions should be working as expected. Users shouldn't see Publications they don't have roles/permission for.
- The Users (and their roles) that are auto-invited to a Publication created from a Template should match the Users (and roles) added to the Template. Basically, no missing Users or Users that shouldn't be invited. 
- Template string tokens should be parsed correctly. Invalid tokens shouldn't be parsed. 
- Since the "Revert Publication" page code is the same as the "Create Publication" page with added conditional rendering (and was rewritten in React), please check that reverting still works as expected

It's a lot but I think that covers the most important things. Please feel free to message me on Slack if you have any questions or something doesn't make sense. Thank you both!

**Comment by xbrianlee** [comment]
@ctang3 As discussed in the weekly, @suilin finished exploratory testing and made some [discoveries](https://issues.liferay.com/browse/LPS-169521?focusedCommentId=2806993&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2806993) that may need to be addressed before we forward this PR. She also began work on the [functional tests](https://issues.liferay.com/browse/LPS-169804) and [test fixes](https://issues.liferay.com/browse/LPS-169659) though some of these changes are blocked by the aforementioned discoveries.

**Comment by david-truong** [comment]
@ctang3 two things I noticed so far was that the validation when creating a publication template causes a lot of noise in the logs when you don't provide the required fields.

Also the success message for inviting users should not happen if you don't actually invite anyone

**Comment by david-truong** [comment]
@ctang3 resent with some of my additions here: https://github.com/liferay-publications/liferay-portal/pull/340

**Pull request closed without merging**
