### PR TITLE
LPS-154710

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee @suilin this has all the latest fixes.  Can you check if the failures?

**Comment by suilin** [comment]
@david-truong, for the upgrade tests most of them are fixed by the PR except upgrading from 7413, and the console log updated on [here](https://gist.github.com/suilin/49605687205e772402fa91d87e8a8a7a), could you look at it?

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
Hi @david-truong, the tests results look good.

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
