### PR TITLE
LPD-25350 Add ctCollectionId to upgrade process queries

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:update

**Comment by noornajj** [comment]
ci:test:layout-page-template

**Comment by noornajj** [comment]
ci:test:upgrade

**Comment by noornajj** [comment]
ci:test:echo

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:2567388566

**Comment by david-truong** [comment]
ci:report:2567388566

**Comment by david-truong** [comment]
ci:report:2567773343

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
