### PR TITLE
LPD-25352 Take ctCollectionId into account for Calendar upgrade process

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-25352

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:calendar

**Comment by brookedalton** [comment]
ci:test:upgrade

**Comment by david-truong** [comment]
ci:test:upgrade

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Pull request closed without merging**
