### PR TITLE
LPS-153069 Add CTCollectionThreadLocal method for setting CTCollectionId to production

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-153069

@tinatian

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-publications/liferay-portal/pull/77

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
