### PR TITLE
LPD-1600 Set autocommit to true for hypersonic when moving changes

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-1600

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
@brookedalton great! how did you discover this?

**Comment by brookedalton** [comment]
Noor helped me! In the first PR I sent you directly I thought that the [documentation](https://www.hsqldb.org/doc/2.0/guide/sessions-chapt.html) was saying "HyperSQL performs automatic commits before and after the execution of such transactions" so assumed autocommit was already true. In the PR I set it to false and was trying to manually do the commits but there were a lot of issues related to that but after speaking with Noor she helped me figure out that it needs to be set to true and there is no need to manually commit anything and it seemed to resolve the issue

**Comment by david-truong** [comment]
@brookedalton we should set autocommit back to the old value after the connection is done. can you add a finally block for that?

**Pull request closed without merging**
