### PR TITLE
Lpd 20820 origin expose bug and rename

### PR DESCRIPTION
**Pull request by slnn**
Updates according to https://github.com/brianchandotcom/liferay-portal/pull/151682#issuecomment-2185847007

Two things:

1. Update the test to expose the TemplateModelException: 
```
Caused by: freemarker.core._TemplateModelException: Java method "com.liferay.portal.tools.sample.sql.builder.DataFactory.newCTEntryModel(long, com.liferay.portal.kernel.model.change.tracking.CTModel, int)" couldn't be called: Can't convert the 1st argument's value to the target Java type, long. The type of the actual value was: string (wrapper: f.t.SimpleScalar)
    
        ----
        FTL stack trace ("~" means nesting-related):
        	- Failed at: ${dataFactory.toInsertSQL(dataFactory...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/macro.ftl" in macro "insertJournalArticle" at line 244, column 17]
        	- Reached through: @insertJournalArticle _ctCollectionId...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/ct_journal_article.ftl" at line 30, column 25]
        	- Reached through: #include "ct_journal_article.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/ct_collection.ftl" at line 59, column 9]
        	- Reached through: #include "ct_collection.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/company.ftl" at line 26, column 9]
        	- Reached through: #include "company.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/sample.ftl" at line 5, column 1]
```
2. Rename these properties

Hi  @ctang3

Could you please confirm if I break anything ?

Thanks
Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
Hi @slnn, I looked through the code and tested the generated data dump from your changes. It doesn't look like your changes broke anything - things look as before plus the JournalArticle insertion is working now. Thank you!

**Comment by ctang3** [comment]
ci:forward

**Pull request closed without merging**
