### PR TITLE
LPS-171363 - Widget Pages run into conflicts in a publication too easily

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin can you help me look at these results

**Comment by david-truong** [comment]
ci:test:sf

**Comment by suilin** [comment]
@david-truong, the rsults look good, all of the failures are not related to the changes.

**Comment by david-truong** [comment]
@suilin can you forward?

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/128544

**Comment by mbowerman** [comment]
@david-truong @xbrianlee What happened with the forward? It appears to have a different set of changes than what I see here.

**Pull request closed without merging**
