### PR TITLE
LPD-1600 Check if there are conflicts after moving the changes to avoid deadlock with hypersonic

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-1600

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
@brookedalton @pei-jung i don't think we should fix it this way.  when we split the check out it means the moveCTEntry service can move incomplete changes.  if anyone uses it directly instead of through the UI it would be broken.  Also we are making this change for hypersonic which isn't even a supported DB.  We need to figure out  to do it via the service only or don't bother to fix it at all.

**Comment by pei-jung** [comment]
I don't think it's worth it to spend more time on this as it's not a supported DB. I'll close this and make a note in the ticket.

**Pull request closed without merging**
