### PR TITLE
LPS-160420 - Display style lost after re-navigating to DM within Publications

### PR DESCRIPTION
**Pull request by david-truong**
@quanhuynhces @locpham97 i actually decided to fix it a different way after studying the code.  We don't want those types of navigation changes to end up in a publication so that is why we are only reading from production.  I updated the code to save any changes to production also.

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee can you check the results of this one?

**Comment by david-truong** [comment]
ci:reevaluate:1367401_2536

**Comment by xbrianlee** [comment]
ci:test:document

@david-truong The failures in the test runs above aren't related to your change. Also I manually tested to check that the bug is fixed. Just need to run some additional tests to make sure we didn't break anything outside of a publication. Can I forward this if tests pass?

**Comment by david-truong** [comment]
@xbrianlee yes please forward if everything checks out

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/127005

**Pull request closed without merging**
