### PR TITLE
LPD-22544 Set ctCollectionId along with CompantThread to persist bufferIncrement in a publication

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-22544

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:2561009743

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:report:2561636883

**Pull request closed without merging**
