### PR TITLE
LPS-181647 - NullPointerException on Startup from SiteIntializer

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:reevaluate:1407401_1544

**Comment by david-truong** [comment]
@xbrianlee can you help me look at this one?

**Comment by xbrianlee** [comment]
ci:test:headless

`relevant` and `publications` test results look good

**Comment by xbrianlee** [comment]
ci:test:headless

Restarting this build due to CI Infra restart

**Comment by xbrianlee** [comment]
ci:forward

`com.liferay.headless.delivery.resource.v1_0.test.CommentResourceTest` failure seems a bit suspicious. Re-running `relevant` to double-check.

**Comment by xbrianlee** [comment]
ci:forward

`com.liferay.headless.delivery.resource.v1_0.test.CommentResourceTest` was aborted in the last run

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
