### PR TITLE
LPS-143350 Rename the Inviter role to Admin

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-143350

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
@tinatian Assigned this ticket to you for review. Test results above look good and we added functional tests to cover this.

**Comment by tinatian** [comment]
@stsquared99 As inviter role had been removed, should we also remove this entry "inviter=Inviter" in language.properties?


Tina.

**Comment by stsquared99** [comment]
@tinatian Yes! Missed that one, thanks

**Comment by stsquared99** [comment]
@tinatian Did you finish reviewing this pull other that than one language key that needs removing? Thanks

**Comment by tinatian** [comment]
@stsquared99 Did you fix the issue I mentioned? I did not see you update this pull.

Tina

**Comment by stsquared99** [comment]
@tinatian This isn't my pull, I'll send a new one. Thanks

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-publications/liferay-portal/pull/16

**Pull request closed without merging**
