### PR TITLE
LPD-17130 Allow only comment owners to perform actions on the comment

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPD-17130

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@ctang3 can you review this one? thanks!

**Comment by ctang3** [comment]
Tested locally and can confirm the fix. Change looks good to me and could be forwarded @pei-jung 

image

**Review by ctang3 — COMMENTED** [review]
Tested locally and can confirm the fix. Change looks good to me and could be forwarded @pei-jung

image

**Comment by pei-jung** [comment]
@noornajj please add test

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Continued with playwright test: https://github.com/liferay-publications/liferay-portal/pull/1245

**Pull request closed without merging**
