### PR TITLE
LPD-25347 Asset upgrade process does not take into account ctCollectionId when upgrading

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-25347](https://liferay.atlassian.net/browse/LPD-25347)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:upgrade

**Comment by gislayne-vitorino** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:2568306380

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
