### PR TITLE
LPS-190389 - As a publication user, I would like a better explanation of what caused the deletion conflict.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@JamesAGarcia can you review the changes

Deletion Modification Conflict → Missing Entity
Modification conflicts with a deletion. → This entity can no longer be updated because it has been deleted in production. Please discard this change to continue with the publish.
Modification Deletion Conflict → Updated Before Deletion
Deletion conflicts with a modification. → You are attempting to delete an entity that has been recently updated in production. You may discard this change and delete the entity again in your publication or discard the change and proceed with the publish.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by JamesAGarcia** [comment]
> Deletion Modification Conflict → Missing Entity
Modification conflicts with a deletion. → This entity can no longer be updated because it has been deleted in production. Please discard this change to continue with the publish.

This is a great improvement. My only comment is that you could simplify the last sentence:
*  "Please discard this change to continue with publishing."
*  "Please discard this change before publishing."
*  "Please discard this change before proceeding."

> Modification Deletion Conflict → Entity Updated Before Deletion
Deletion conflicts with a modification. → You are attempting to delete an entity that has been recently updated in production. You may discard this change and delete the entity again in your publication or discard the change and proceed with the publish.

The first sentence is great, though the second sentence feels a bit too full. I could see doing something like this:

* Please discard the deletion. Then you can publish your remaining changes or delete the entity again before proceeding.
* Please discard the deletion. Then you may delete the entity again before publishing your changes.
* Please discard the deletion. Then you may delete the entity again before publishing.

Let me know if you'd like more alternatives.

**Comment by david-truong** [comment]
@JamesAGarcia do you have any suggestions for: Modification Deletion Conflict → Entity Updated Before Deletion...

I actually think we don't get much from these descriptions and would prefer we just remove them but it would require us to ensure all conflicts have really nice explanations

**Comment by david-truong** [comment]
@xbrianlee do the tests need to be updated since I modified the messages?

**Comment by xbrianlee** [comment]
@david-truong They do. I'll start on this. After the test fixes, is this PR ready to be forwarded?

**Comment by JamesAGarcia** [comment]
@david-truong 

Missing Entity is far better than Deletion Modification Conflict

Entity Updated Before Deletion is also better than Modification Deletion Conflict, and I haven't thought of a better title. I had "modified before deletion," but it seems like including entity would be more consistent with the missing entity title.

Personally, I think having a short title along with the conflict description is helpful. It makes the conflicts easier to reference in the docs and provides a short-hand for people working with publications.

**Comment by david-truong** [comment]
It is good to go

**Comment by xbrianlee** [comment]
Running tests in https://github.com/xbrianlee/liferay-portal/pull/1317. Will forward that PR once the tests look good.

**Comment by suilin** [comment]
The tests results look good on https://github.com/xbrianlee/liferay-portal/pull/1317 and it has been forwarded.

**Pull request closed without merging**
