### PR TITLE
LPS-198917 Hide FragmentEntryLinks if its layout is hidden

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Review by david-truong — APPROVED** [review]

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:forward:force

**Pull request closed without merging**
