### PR TITLE
LPS-161619, LPS-161621 - Enable CT for Phone and Address

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-161619
https://issues.liferay.com/browse/LPS-161621

@david-truong

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee can you look at the results?

**Comment by xbrianlee** [comment]
ci:test:usm

**Comment by xbrianlee** [comment]
ci:test:publications-db

**Comment by xbrianlee** [comment]
ci:test:upgrade

**Pull request closed without merging**
