### PR TITLE
LPS-183473 - While in a Publication, entities deleted in Recycle Bin are deleted permanently

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee i have prevented the ability to empty recycle bin in a publication.  do we need to update the tests?

**Comment by xbrianlee** [comment]
@david-truong Yeah we would need to.

Btw if we don't allow assets to be emptied from the Recycle Bin, they won't be able to be deleted within a Publication. Moving assets to the Recycle Bin counts as a modification. Is this what we want to do?

**Comment by david-truong** [comment]
@xbrianlee yeah that seems correct.  when you delete from the recycle bin, can you publish afterwards?  I think you break the publication.

**Comment by david-truong** [comment]
@suilin can you update the tests to not empty from recycle bin.  also add a test to ensure you can't empty in a publication.

**Comment by xbrianlee** [comment]
@david-truong
> When you delete from the recycle bin, can you publish afterwards?
You can. This is currently how we are able to delete WC, documents, etc within a publication.

**Comment by suilin** [comment]
@david-truong, 

- I updated the tests to not empty from recycle bin, and I sent the PR on https://github.com/liferay-publications/liferay-portal/pull/537; 
- I didn't add a test to ensure you can't empty in a publication since now we can do it. 
- Wiki node and wiki page changes will display as nodeId and pageId in the review changes page after moving them to Recycle Bin, is it the expected result?
ActualResult

cc @xbrianlee

**Pull request closed without merging**
