### PR TITLE
LPD-27495 Remove classNameId from the ServiceTrackerMap

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-27495

### CODE REVIEW

**Comment by david-truong** [comment]
Can you rename both of them to spi.history

**Comment by brookedalton** [comment]
ci:test:sf

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
