### PR TITLE
LPD-33274 Disable Publish button after first click when publishing a publication

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-33274

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
https://github.com/user-attachments/assets/3b4ebb86-64e1-4db4-8ff6-ef8c5039fe67

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
