### PR TITLE
LPS-157454 Part 1: Cache LayoutStructure in ContentPageEditorDisplayContext | init in constructor

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is basically same with https://github.com/liferay-publications/liferay-portal/pull/140, I just moved LayoutStructure to constructor as Echo Team confirms that both portlets are always on the same page..

### CODE REVIEW

**Comment by xbrianlee** [comment]
@tinatian It looks like most of these functional tests are failing due to the fragments sidebar failing to load ([example](https://testray.liferay.com/reports/production/logs/2022-07/test-1-31/test-portal-acceptance-pullrequest%28master%29/4064/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz), [console log](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/95339/consoleText)). 

```
[beanshell] 2022-07-07 15:23:31.027 ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._initLayoutStructure(ContentPageEditorDisplayContext.java:2065) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext.<init>(ContentPageEditorDisplayContext.java:211) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageLayoutEditorDisplayContext.<init>(ContentPageLayoutEditorDisplayContext.java:115) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextProvider.getContentPageEditorDisplayContext(ContentPageEditorDisplayContextProvider.java:74) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.portlet.ContentPageEditorPortlet.doDispatch(ContentPageEditorPortlet.java:77) ~[?:?]
[beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:113) ~[portal-kernel.jar:?]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:568) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:658) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:343) ~[portal-impl.jar:?]
[beanshell] 2022-07-07 15:23:31.398 ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._initLayoutStructure(ContentPageEditorDisplayContext.java:2065) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext.<init>(ContentPageEditorDisplayContext.java:211) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageLayoutEditorDisplayContext.<init>(ContentPageLayoutEditorDisplayContext.java:115) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextProvider.getContentPageEditorDisplayContext(ContentPageEditorDisplayContextProvider.java:74) ~[?:?]
[beanshell] 	at com.liferay.layout.content.page.editor.web.internal.portlet.ContentPageToolbarPortlet.doDispatch(ContentPageToolbarPortlet.java:77) ~[?:?]
[beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:113) ~[portal-kernel.jar:?]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:568) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:658) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:343) ~[portal-impl.jar:?]
     [exec]     LIFERAY_ERROR: null
```

**Comment by dantewang** [comment]
> @tinatian It looks like most of these functional tests are failing due to the fragments sidebar failing to load even when Publications is not enabled ([example](https://testray.liferay.com/reports/production/logs/2022-07/test-1-31/test-portal-acceptance-pullrequest%28master%29/4064/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz), [console log](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/95339/consoleText)). 
> 
> ```
> [beanshell] 2022-07-07 15:23:31.027 ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
> [beanshell] java.lang.NullPointerException: null
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._initLayoutStructure(ContentPageEditorDisplayContext.java:2065) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext.<init>(ContentPageEditorDisplayContext.java:211) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageLayoutEditorDisplayContext.<init>(ContentPageLayoutEditorDisplayContext.java:115) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextProvider.getContentPageEditorDisplayContext(ContentPageEditorDisplayContextProvider.java:74) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.portlet.ContentPageEditorPortlet.doDispatch(ContentPageEditorPortlet.java:77) ~[?:?]
> [beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
> [beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
> [beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:113) ~[portal-kernel.jar:?]
> [beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:568) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:658) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:343) ~[portal-impl.jar:?]
> [beanshell] 2022-07-07 15:23:31.398 ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
> [beanshell] java.lang.NullPointerException: null
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext._initLayoutStructure(ContentPageEditorDisplayContext.java:2065) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext.<init>(ContentPageEditorDisplayContext.java:211) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageLayoutEditorDisplayContext.<init>(ContentPageLayoutEditorDisplayContext.java:115) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextProvider.getContentPageEditorDisplayContext(ContentPageEditorDisplayContextProvider.java:74) ~[?:?]
> [beanshell] 	at com.liferay.layout.content.page.editor.web.internal.portlet.ContentPageToolbarPortlet.doDispatch(ContentPageToolbarPortlet.java:77) ~[?:?]
> [beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
> [beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
> [beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:113) ~[portal-kernel.jar:?]
> [beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
> [beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:568) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:658) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:343) ~[portal-impl.jar:?]
>      [exec]     LIFERAY_ERROR: null
> ```

Thanks, I think I know where the issue is. I put the init method before assigning this.httpServletRequest. Will force push later.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:publications

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:acceptance

**Comment by xbrianlee** [comment]
ci:test:echo

**Comment by xbrianlee** [comment]
The last wave of results look good. Running one more round of tests to make sure this didn't break anything for Echo team.

**Comment by xbrianlee** [comment]
@dantewang I noticed one new failure that may seems to be related to your changes. Could you take a look?
1. Navigate to Product Menu > Design > Page Template
2. Add a custom master
3. Within the custom master, add a Tabs fragment
4. Move master page template drop zone to Tab 1 of Tab Fragment
5. Publish master page template
6. Add a page basing on custom master

Expected results: User can see the drop zone in Tab 1
Actual result: User can't see the drop zone in Tab 1

**Comment by dantewang** [comment]
@tinatian I'm going to close this one and wait for Echo Team to handle the LayoutStructure management.

The bug @xbrianlee mentioned is caused by this change. In the context of editing a page which has a master page, the LayoutStructure created in ContentPageEditorDisplayContext is of the page being edited, without content from its master page. However, the processor, e.g. `DropZoneFragmentEntryProcessor`, can still process the fragment on the master page in the same request processing chain. So we can't simply cache the LayoutStructure created in the display context...

**Pull request closed without merging**
