### PR TITLE
LPS-192949 Deletion Modification Conflict for DDM Structures should not be edited

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-192949](https://liferay.atlassian.net/browse/LPS-192949)

### CODE REVIEW

**Comment by pei-jung** [comment]
@gislayne-vitorino Do not revert the changes for LPS-147406. We still want the edit url to work when viewing the changes in publications. What we want to do instead is to hide the Edit button in the actions menu when the change is a Deletion Modification conflict.

image

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
sorry wrong ticket

**Comment by david-truong** [comment]
I closed the one sent to Brian.  @gislayne-vitorino you might want to just resend a new PR since @pei-jung is asking for a different fix

**Pull request closed without merging**
