### PR TITLE
LPS-183473 - While in a Publication, entities deleted in Recycle Bin are deleted permanently

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin I think I broke the tests again

**Comment by suilin** [comment]
@david-truong, I updated the tests according to the new changes, and I sent them on https://github.com/liferay-publications/liferay-portal/pull/541.

And I'd like to confirm with you about the following results, could you help to look at if they are expected?
- We still can empty the recycle bin and publish the publication successfully.

- After moving to recycle bin, the change type changes to Delete, but the conflict message doesn't update, it shows `Modification Conflict: The conflict cannot be automatically resolved.` the expected one should be
`Deletion Modification Conflict: Modification conflicts with a deletion.`?

- * Wiki node&wiki page, web content folder changes will display as nodeId and pageId in the review changes page after moving them to Recycle Bin.
ActualResult

cc @xbrianlee

**Comment by david-truong** [comment]
- you can not empty the recycle bin in a publication.  Can you show me the steps where you are able to do this?
- we aren't changing the conflict message.  How are you generating the conflict?
- I can double check why it's doing that but it should keep the same original name ideally

**Comment by suilin** [comment]
@david-truong, sorry for making you confused, I will update the steps of the bug as follows:

- We still can empty the recycle bin and publish the publication successfully. But the expected result should be we cannot empty the recycle bin within Publications.
1. Enable Publications
2. Add a new web content
3. Add a new publication
4. Move the new web content to recycle bin
5. Empty the recycle bin
6. Publish the publication

- After moving to recycle bin, the change type changes to Delete, but the conflict message doesn't update.
1. 1. Enable Publications
2. Add a new web content
3. Add a new publication "P1"
4. Edit the web content
5. Add a new publication "P2"
6. Move the web content to recycle bin
7. Review changes of "P2"
8. The change type is deleted
9. Publish "P2"
10. Go to publish "P1"
11. "P1" cannot publish due to the conflict and it shows `Modification Conflict: The conflict cannot be automatically resolved.`  The expected should be `Deletion Modification Conflict: Modification conflicts with a deletion.`

cc @xbrianlee

**Pull request closed without merging**
