### PR TITLE
LPS-199500 Find groupId for pages added in the publication

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-199500

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@xbrianlee the stable failure doesn't seem related. Can you manually forward?

**Comment by brookedalton** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/144007

**Pull request closed without merging**
