### PR TITLE
LPS-161979 remove published CTSContent data

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:reevaluate:1377401_4696

**Comment by david-truong** [comment]
ci:reevaluate:1357401_2486

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/122594

**Pull request closed without merging**
