### PR TITLE
LPS-173968 - As a publications user, I should be able to configure if unapproved changes should be publishable

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 see my changes.  I also made some small changes with the wording that i squashed into your original changes.

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by suilin** [comment]
@david-truong, all of the failures are caused by LPS-173843 (https://github.com/liferay-publications/liferay-portal/pull/433), they are not related to current changes, could we forward it?

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
