### PR TITLE
LPD-33743 Set width to auto for Publications table

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-33743

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@ctang3 can you review this? Thanks!

**Comment by ctang3** [comment]
Changes look good to me! No more scroll bar. Thanks @brookedalton!

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
