### PR TITLE
LPD-21520 Add workflow actions to the dropdown menu

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@gislayne-vitorino why do we have to reload the portlet?

**Comment by gislayne-vitorino** [comment]
@david-truong  We are using the contents from Workflow portlet to build the pop ups, so the reload is needed to redirect  back to our portlet

**Comment by pei-jung** [comment]
Actually the reload is used to update the dropdown menu and the assignee field. However, the selected tab is not preserved when page is refreshed. We'll need to update and reload the react component instead. This should be fixed with the success message bug that I'm currently working on.

**Comment by pei-jung** [comment]
@gislayne-vitorino please see my changes in https://github.com/liferay-publications/liferay-portal/pull/1156.

**Pull request closed without merging**
