### PR TITLE
LPS-187183 - As a publication user, I would like to review the changes related to User Experiences added to a Publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee @suilin can you rebase the test fixes with the branch

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
Rebased and running tests in https://github.com/xbrianlee/liferay-portal/pull/1319

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141489

**Pull request closed without merging**
