### PR TITLE
LPS-159988 - Add/Edit Workflow Definition and SLA within Publications are in Production mode

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin I couldn't follow the bug completely so I wasn't sure what I was attempting to fix but I did notice one issue with the search results not showing up properly when in a publication.

**Comment by david-truong** [comment]
@suilin can you check to see if everything is working and forward if everything looks good?

**Comment by suilin** [comment]
@david-truong the results look good and I did the smoke test for workflow admin, everything works fine, I will forward it.

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:stop

**Comment by suilin** [comment]
@david-truong, I did the exploring testing and I'd like to confirm with you wether all of the operations within Publications (Workflow Admin) will thansfer to production automatically, but the following won't be in production mode, they are still only in publication mode, do you think they are expected result?
- Duplicate, Unpublish and Delete the publication
- Configurate the Asset workflow through Process Builder > Configuration

**Comment by david-truong** [comment]
Ok I'll check those scenarios

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:reevaluate:1267401_5118

**Comment by joshchong** [comment]
Reran the failing test `WorkflowMetrics#ViewWorkloadByAssigneeCard` in https://github.com/joshchong/liferay-portal/pull/600#issuecomment-1255544175 and verified it was a fluke.

**Comment by joshchong** [comment]
Manually forwarded to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/123585

**Pull request closed without merging**
