### PR TITLE
LPS-198982 It is possible to publish a draft layout without an associated published layout to Production

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@david-truong I asked the echo team to review this [change](https://github.com/liferay-publications/liferay-portal/pull/796/commits/148c09eef4e602290891c2ce7f88cd8412e2ecea) in https://github.com/liferay-echo/liferay-portal/pull/14104. If they approve, we don't have to hack the query.

**Comment by pei-jung** [comment]
@david-truong fyi, echo team approves the changes so now all the layouts should be approved when LayoutPageTemplateEntry is published.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee can you add tests for this? I added the test cases in https://liferay.atlassian.net/browse/LPS-198982?focusedCommentId=2493361. We don't need to send the tests with this PR; they can be sent separately later.

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
@pei-jung, I finished the publications suite and found lots of issues caused by the following issue, can you look at it?

Cannot publish the publication with site change.
1. Enable Publications
2. Add new publication
3. Add a new site
4. Publish the publication
Result: `This publication contains unapproved changes that must be approved before publishing.` message shows up and cannot be published.

cc @xbrianlee 

Note: Lots of the tests are aboard in Relevant suite and I re-triggered it but it's pending for a long time.

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
Merged upstream
https://github.com/brianchandotcom/liferay-portal/pull/142781

**Pull request closed without merging**
