### PR TITLE
LPS-170725 - My account actions are not forced to production

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee can you help me look at these results

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:object

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/127766

**Pull request closed without merging**
