### PR TITLE
LPS-178606 - Fail to add fragment in a new site within Publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee  can you look at these results

**Comment by xbrianlee** [comment]
ci:test:document

Test results above look good. Running this test suite since we're changing the `document-library` module.

**Comment by xbrianlee** [comment]
@david-truong Test results here look good 👍

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
