### PR TITLE
LPS-198324 - Remove feature flag in stories under LPS-185308

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
waiting for https://github.com/liferay-publications/liferay-portal/pull/825 to merge first:

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee @suilin i assume we are going to have to make more test changes because of the removal of the old changes view

**Comment by suilin** [comment]
@david-truong, I'm working on refactoring the tests and I did the first round of analysis, I found an issue that only can be reproduced on current commits, the Show System Changes is always Hide System Changes
outofdataPublications. 

And I created two new issues [LPS-201365](https://liferay.atlassian.net/browse/LPS-201365) and [LPS-201369](https://liferay.atlassian.net/browse/LPS-201369) and the [issues](https://liferay.atlassian.net/issues/?filter=14292) that created before, Do you think we need to prioritize these issues? Thanks

**Comment by david-truong** [comment]
@suilin i fixed the link issue

**Comment by suilin** [comment]
ci:test:bundle

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by suilin** [comment]
The relevant suite failures are not related to current changes, I re-fetch the branch and did the test fixes on https://github.com/suilin/liferay-portal/pull/692, I will close the PR.

**Pull request closed without merging**
