### PR TITLE
LPS-200185 - As a headless developer, I would like to schedule, publish, and get the share link of a Publication via external reference code

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you help me review the results

**Comment by xbrianlee** [comment]
@david-truong The semver error for `/apps/change-tracking/change-tracking-rest-client` is related to these changes. The other results look good.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/142937

**Pull request closed without merging**
