### PR TITLE
LPS-182238 phone address fixes

### PR DESCRIPTION
**Pull request by ctang3**
- https://issues.liferay.com/browse/LPS-161621?focusedCommentId=2902088&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2902088
- https://issues.liferay.com/browse/LPS-161619?focusedCommentId=2902093&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2902093

@xbrianlee @david-truong 
All the issues mentioned in your comments should be fixed by these changes, based on my testing

### CODE REVIEW

**Comment by xbrianlee** [comment]
@ctang3 The semver issue is related to these changes. Can you take a look?
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell]   com.liferay.portal.kernel.security.permission      UNCHANGED  7.0.0      6.5.0      6.5.0      EXCESSIVE VERSION INCREASE
[beanshell] 	-   version    6.5.0
[beanshell] 	+   version    7.0.0
```

**Comment by ctang3** [comment]
Hey @xbrianlee Just to confirm, these failures are triggered when publishing and are not database conflict errors in the logs? I wasn't seeing it initially because I was using these steps below, but I did see a publishing conflict when trying to publish.

1. Add an Organization (tried with and without adding an address or phone in Production)
2. Enable Publications
3. Edit the added Organization > Contact tab > Addresses/Contact Information
4. Add an Address or Phone number to that Organization
5. Address/Phone is successfully added for me, no errors in the portal logs

**Comment by xbrianlee** [comment]
@ctang3 Sorry I wasn't clear! I'm referring to conflicts while publishing.

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by david-truong** [comment]
resent with fixes here: https://github.com/liferay-publications/liferay-portal/pull/570

**Pull request closed without merging**
