### PR TITLE
LPS-183473 - While in a Publication, entities deleted in Recycle Bin are deleted permanently

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin i comfirmed the data does indeed switch the title to the trashEntry Id when it gets deleted.  I have no idea why it does that but it does indeed change.

**Comment by suilin** [comment]
@david-truong, the confused one is the trashEntry Id doesn't have the same id as the wikiNode Id and wikiPage Id, so it's hard for us to get it and assert the changes display.

For the other bugs, I updated the steps on https://github.com/liferay-publications/liferay-portal/pull/538#issuecomment-1539271332, could you help to look at them?

**Comment by suilin** [comment]
@david-truong, I re-send to https://github.com/liferay-publications/liferay-portal/pull/549 
* Add a new functional test to assert we cannot empty recycle bin in a publication.
* Work around the steps to view the wiki node/page changes after moving to recycle bin. 
* I will update the test after you confirmed with the issue I memtioned above.

**Comment by david-truong** [comment]
the issue mentioned above is the correct behavior.

**Comment by suilin** [comment]
@david-truong, I'm a little confused about the result, the change type is `Delete` after moving to recycle, but when there is a conflict it shows that it's `modification` instead of deletion, so do you think there are contradictory?

**Comment by david-truong** [comment]
it's not a real delete.  the system actually considers it a modification.  we are only showing delete in the ui to make it less confusing for the ui.  Can you create a story instead for the conflict.  I think we can resolve the conflict automatically for the user.

**Comment by david-truong** [comment]
I think we can just move the content out of the recycle bin automatically for the user

**Pull request closed without merging**
