### PR TITLE
LPS-187183 experience selector

### PR DESCRIPTION
**Pull request by ctang3**
The currently active experience is the initial item selected by the selector. Before this change, it showed the active experience but always loaded the 'DEFAULT' experience so there was a mismatch between what the user sees and what the selector says is the currently selected experience. Now, the page experience the user sees when clicking on the page change entry is determined by the active experience is (since multiple experiences' changes are bundled per page, and switched between with the Experience Selector).

https://liferay.atlassian.net/browse/LPS-187183

@david-truong

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
Aborted the run above. Running tests in https://github.com/xbrianlee/liferay-portal/pull/1319 with functional test fixes.

**Comment by xbrianlee** [comment]
Test results with test fixes in https://github.com/xbrianlee/liferay-portal/pull/1319 look good

**Comment by david-truong** [comment]
@ctang3 can you fix the conflict?

**Comment by xbrianlee** [comment]
Rebased and running tests in https://github.com/xbrianlee/liferay-portal/pull/1319.

@david-truong @ctang3 Are these changes good to go if CI passes?

**Comment by david-truong** [comment]
resent with fix for last commit: https://github.com/liferay-publications/liferay-portal/pull/713

**Pull request closed without merging**
