### PR TITLE
LPD-20756, LPD-20820 - Generate pages and webcontent data

### PR DESCRIPTION
**Pull request by ctang3**
Combining these into a single PR since LPD-20820 depends on LPD-20756. Also attached is the generated data dump in MySQL format and my modified SampleSQLBuilderTest.java for easier local testing and data generation.

- https://liferay.atlassian.net/browse/LPD-20756
- https://liferay.atlassian.net/browse/LPD-20820

📁 [LPD-20820_sample-mysql.zip](https://github.com/liferay-publications/liferay-portal/files/15181243/LPD-20820_sample-mysql.zip)
📁 [Modified_SampleSQLBuilderTest.zip](https://github.com/liferay-publications/liferay-portal/files/15181262/Modified_SampleSQLBuilderTest.zip)

### CODE REVIEW

**Comment by pei-jung** [comment]
I'm getting this exception:
```
2024-05-09 16:34:23.986 ERROR [http-nio-8080-exec-5][ExceptionMapper:59] null
java.lang.NullPointerException: null
	at com.liferay.change.tracking.rest.internal.dto.v1_0.converter.CTCollectionDTOConverter._getStatusMessage(CTCollectionDTOConverter.java:136) ~[?:?]
	at com.liferay.change.tracking.rest.internal.dto.v1_0.converter.CTCollectionDTOConverter.access$000(CTCollectionDTOConverter.java:41) ~[?:?]
	at com.liferay.change.tracking.rest.internal.dto.v1_0.converter.CTCollectionDTOConverter$1.lambda$new$2(CTCollectionDTOConverter.java:77) ~[?:?]
	at com.liferay.change.tracking.rest.dto.v1_0.CTCollection.lambda$setStatusMessage$10(CTCollection.java:500) ~[?:?]
	at com.liferay.change.tracking.rest.dto.v1_0.CTCollection.getStatusMessage(CTCollection.java:480) ~[?:?]
```

Looks like `createDate` and `modifiedDate` are missing for the CTCollections
Screen Shot 2024-05-09 at 9 40 03 AM

Also, why are we adding so many different publications?

**Comment by ctang3** [comment]
@pei-jung Fixed the createDate and modifiedDate. The number of publications was due to it using the wrong Benchmark property for the # to create. Fixed it so it should be 1 for the main site and 1 for the publications testing specific site.

**Comment by ctang3** [comment]
DB Dump with the create/modified date changes:

[sample-mysql_with-date-changes.zip](https://github.com/liferay-publications/liferay-portal/files/15425338/sample-mysql_with-date-changes.zip)

**Comment by pei-jung** [comment]
@ctang3 TODOs per our discussion. Let's try to get the pages working first
- [ ] Enable publications using `ConfigurationProviderUtil`
- [ ] Add missing createDate and modifiedDate for ctEntries
- [ ] Make Publication Group a site so it's visible

Skip the web contents for now
- [ ] Add web contents in publication

Please resend a new PR when you're done.

**Pull request closed without merging**
