### PR TITLE
LPS-186677 - As a publication user, I would like to configure the context view to display production entities

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj can you try this with the client's data to see if it helps?

**Comment by david-truong** [comment]
@suilin can you take a look at the results?

**Comment by suilin** [comment]
@david-truong, the failures are not related to current changes, should we forward it?

**Comment by noornajj** [comment]
@david-truong 
I tested this with the sample data provided in the customer ticket and the review page now loads very fast

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
reopening to reconsider a different way to possibly build the CTClosure after talking to @tinatian

**Pull request closed without merging**
