### PR TITLE
LPS-170104 - Content pages does not get approved for workflow when approved in a publication.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee this one is high priority can you help follow it so make sure we discover any issues ASAP or forward it if it looks good.

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Test failures from the test suites above don't appear to be related. Closing this PR since the changes have already been merged.

**Pull request closed without merging**
