### PR TITLE
LPD-28970 Error viewing data tab after viewing workflow tab

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-28970

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
Behavior before change:

https://github.com/liferay-publications/liferay-portal/assets/46908843/0edbda98-36b7-4da6-aa25-3e15b1374418

Behavior after change:

https://github.com/liferay-publications/liferay-portal/assets/46908843/ba27895a-83f7-4a17-b790-12e18f931871

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
