### PR TITLE
LPS-183191 Documents Folder and Permission Changes shows up when browsing Publishing Import

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for:[LPS-183191](https://issues.liferay.com/browse/LPS-183191)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
rebased: https://github.com/liferay-publications/liferay-portal/pull/571

**Pull request closed without merging**
