### PR TITLE
LPD-25832 Asset Display upgrade process does not take into account ctCollectionId when upgrading

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:echo

**Comment by gislayne-vitorino** [comment]
ci:test:upgrade

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:upgrade

**Comment by gislayne-vitorino** [comment]
ci:test:echo

**Comment by david-truong** [comment]
@gislayne-vitorino can you rebase to include the revert and resend

**Comment by gislayne-vitorino** [comment]
Hey @david-truong , the revert commit is already included in this pr, you can check it [here](https://github.com/liferay-publications/liferay-portal/pull/1208/commits/5b3dd152164d5ae7dac2560a97968ca7dd23b653)

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:2571666282

**Comment by david-truong** [comment]
ci:report:2571671394

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
