### PR TITLE
LPS-175323 - FragmentEntryLink table definition references defined incorrectly

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee  can you help me check the results and forward?

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@xbrianlee woah this one passed all the publication tests!

**Comment by xbrianlee** [comment]
@david-truong Yeah we finally got around to cleaning up the test suite this week. Hopefully it's a bit more stable from now on.

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
