### PR TITLE
LPS-157936 Create Upgrade to remove existing orphaned PortletPreferences

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-157936

This is a subtask of https://issues.liferay.com/browse/LPS-156786
- Original ticket PR: https://github.com/brianchandotcom/liferay-portal/pull/120031

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by ctang3** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:echo

**Comment by xbrianlee** [comment]
@ctang3 The results from the previous `publications`, `publications-environments`, `relevant`, and `echo` test runs look good for the most part. The only regression I found was for [FragmentsUpgrade#ViewFragmentWithEmbeddedInstantiableWidgetAfterUpgradeFrom71105](https://testray.liferay.com/home/-/testray/case_results/1905789963):
- Steps prior to upgrading: [LPS-153275](https://issues.liferay.com/browse/LPS-153275) ([database dump](https://github.com/liferay-publications/liferay-portal/files/9113745/data-archive-fragment-with-instantiable-widget-mysql.zip))
- After upgrade, navigate to Test Page Name on Test Site Name. The Web Content Display widget should show the fragment we created prior to the upgrade.

**Comment by ctang3** [comment]
Closing this PR to reopen a new one for clarity.

**Pull request closed without merging**
