### PR TITLE
LPS-184800 - Can not publish with expired content

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:reevaluate:1327401_9842

**Comment by david-truong** [comment]
ci:reevaluate:1307401_6696

**Comment by david-truong** [comment]
@xbrianlee can you help me look at these results

**Comment by xbrianlee** [comment]
ci:test:publications

Re-running since there were many tests that failed to run

**Comment by david-truong** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:publications:norebase

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
