### PR TITLE
LPD-26729 - PortalLogAssertorTest Failed session factory verification with LayoutPageTemplateStructureRelUpgradeProcessTest

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:upgrade

**Comment by david-truong** [comment]
ci:report:2573129997

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:test:echo

**Pull request closed without merging**
