### PR TITLE
LPS-183473

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-183473
https://issues.liferay.com/browse/LPS-183732
https://issues.liferay.com/browse/LPS-183985

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin do the tests need updating?  seems like we are getting more failures than before

**Comment by suilin** [comment]
@david-truong, this pr doesn't contain the conflict message commit, and I send it now, the results should be good now. After you fixed [LPS-184133](https://issues.liferay.com/browse/LPS-184133) I will re-update the tests.

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
@david-truong, the results look good, do we need to forward it?

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:reevaluate:1377401_11394

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
