### PR TITLE
LPS-193854 - Add Service Account and OAuth2 Application for Remote Publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee i resent with fixes

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@suilin i updated to address the final issue

**Comment by suilin** [comment]
Hi @david-truong, the results look good, everything works fine according to the Acceptance Criteria of LPS-193854, I'm going to forward it.

cc @xbrianlee

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:forward:force

**Pull request closed without merging**
