### PR TITLE
LPD-33399 Fix [$PORTAL_URL$] replacement

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@abfranca Would you mind adding a test and perhaps some steps to reproduce the issue this is trying to solve? Thank you!

**Comment by abfranca** [comment]
@jonathanmccann Hi! By adding a test you mean in the BundleSiteInitializerTest class? Also the steps to reproduce would be on the ticket? But sure, I can do that, just want to clarify these details first.

**Comment by jonathanmccann** [comment]
@abfranca Yes, sorry for not being clear!

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
Looks good to me! Thanks for adding the test. Once the CI passes this can be forwarded.

**Comment by jonathanmccann** [comment]
Failing tests are unrelated. Forwarding.

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
@abfranca Please see https://github.com/liferay-publications/liferay-portal/pull/1336

There were some failing tests due to the `getServiceContext` method now throwing an exception so I updated those. I also squashed down the SF commits to make it a bit cleaner. If anything looks off please let me know otherwise once the tests pass there I'll forward it along.

**Comment by jonathanmccann** [comment]
ci:close

**Comment by abfranca** [comment]
Thank you @jonathanmccann !

**Pull request closed without merging**
