### PR TITLE
LPS-181233 Fix indexing bug to make the reindex process work better across publications

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-181233](https://issues.liferay.com/browse/LPS-181233).

In [LPS-157814](https://issues.liferay.com/browse/LPS-157814), we added a new CTSQLMode called CT_ALL, which bypassing the SQL-changing logic. The purpose of this was for reindexing, so that we could iterate over all items when reindexing instead of just those on whatever CTCollection we happened to have checked out.

The problem is, we really only want to bypass the SQL-changing logic during the fetching of the objects to be reindexed. Once we actually start reindexing the objects, we need the SQL-changing logic to be present again. For example, if we wish to fetch an associated object by primary key (such as the tags associated to the asset), we need the SQL-changing logic to be applied for that query. Otherwise, we might fetch multiple objects for one primary key, which confuses Hibernate and causes it to throw errors.

This fix applies the CTThreadLocals back to the appropriate values for the ctCollectionId that the object-to-be-indexed belongs to (or 0/Production if the object is not a CTModel). In order to accomplish this, I needed to move the CTSQLModeThreadLocal class into portal-kernel. Please let me know if you have any concerns about this, or any questions about this fix.

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj can you review this one?

**Comment by mbowerman** [comment]
I've force-pushed an SF fix, and now the CI SF test has passed.

**Comment by noornajj** [comment]
Started looking into this

**Comment by david-truong** [comment]
@xbrianlee can you look at the results and forward if it looks good?

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
`publications` and `relevant` results look fine. Running `search` suite since portal-search was changed.

Manual testing passed following the steps in the ticket with the bundle from [this run](https://github.com/liferay-publications/liferay-portal/pull/494#issuecomment-1504042344). The functional test to cover this use case will be added in a separate PR soon.

**Comment by david-truong** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
