### PR TITLE
LPD-2228 Failed upgrade process for module com.liferay.change.tracking.web on DB2

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-2228

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:publications-db

**Comment by brookedalton** [comment]
[PublicationsUpgrade#ViewNoUnrelatedPreviewsArchive7310](https://testray.liferay.com/#/project/34754/routines/34756/build/34549092/case-result/34568177 ) is passing in CI, PublicationsUpgrade#ViewNoUnrelatedPreviewsArchive7413 no longer exists

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
