### PR TITLE
LPS-193130 Change when portlet preferences appear on Review Changes screen

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-193130](https://liferay.atlassian.net/browse/LPS-193130)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee can you help review the test results?

**Comment by suilin** [comment]
Hi @pei-jung, the reuslts look good, the failures are not related to current change, should we forward it?

cc @xbrianlee

**Comment by pei-jung** [comment]
Thanks @suilin. This is ready to forward.

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
