### PR TITLE
LPS-182960 - Performance tuning for discarding a change with large amount of Publications changes

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@suilin can you give me the steps to test the 2 failing issues with discarding

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
Results above look good. Forwarding with test fixes in https://github.com/xbrianlee/liferay-portal/pull/1215.

**Pull request closed without merging**
