### PR TITLE
LPS-186466 - Can not publish publication with a page when that has modified expando values

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you look at the results

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
