### PR TITLE
LPS-190241 Right side of the Split View should show the Publication's name

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPS-190241

@david-truong 

Right side now shows the publication's name instead of a generic "PUBLICATION" like below: 

image

### CODE REVIEW

**Comment by david-truong** [comment]
@gislanye-vitorino take a look at how this was implemented

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin can you check the results

**Comment by david-truong** [comment]
@xbrianlee are the failures related?

**Comment by xbrianlee** [comment]
@david-truong This PR just needs test fixes. I'll start on them shortly.
https://liferay.atlassian.net/browse/LPS-191421

**Comment by xbrianlee** [comment]
Running with test fixes in https://github.com/xbrianlee/liferay-portal/pull/1277

**Pull request closed without merging**
