### PR TITLE
LPS-189287 - Add External Reference Code to CTCollection

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@suilin can you check the results?

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
@david-truong, I also triggered the publications-db suite, all of the results look good, should we forward it?

cc @xbrianlee

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Comment by suilin** [comment]
Hi @david-truong, there is a conflict for `modules/apps/change-tracking/change-tracking-service/bnd.bnd`, can you look at it? Thanks.

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
