### PR TITLE
LPS-190390 - As a publication user, I would like a better explanation of what caused the modification conflict.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@JamesAGarcia can you review this one also

Modification Conflict → Entity Already Updated
The conflict cannot be automatically resolved → This entity has been updated in production. It was not possible to automatically resolve the conflict. Please discard the change. Then you may update the entity again before publishing your changes.

**Comment by david-truong** [comment]
@xbrianlee you might need to update the tests for this pr also

**Comment by xbrianlee** [comment]
@david-truong Ok! I'll keep an eye on the results. Thanks for the heads up!

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by JamesAGarcia** [comment]
"Entity Recently Updated" is a little clearer to me. "Already" could imply that the change from the publication was *already* applied to production.

As for the description, I'd go with something like this:
* "This entity has been updated in production. Please discard the change. Then you can update the entity again before publishing."
* "This entity has been updated in production and Publications cannot resolve the conflict automatically. Please discard the change. Then you can update the entity again before publishing."

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee this is ready for you to add any test fixes.

**Comment by david-truong** [comment]
@xbrianlee @suilin is this one okay to forward or do we need to update the tests?

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
@david-truong This PR still requires test fixes. We'll get this forwarded on Monday.

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@david-truong The `com.liferay.change.tracking.internal.conflict.test.CTColumnResolutionMaxTest` failure is unique to this PR. Can you take a look at this?
https://testray.liferay.com/home/-/testray/case_results/2430069100

No new functional tests need to be added for this PR but I'm working on fixing a few of our existing ones.

**Comment by xbrianlee** [comment]
Testing functional test fixes in https://github.com/xbrianlee/liferay-portal/pull/1321

**Comment by david-truong** [comment]
@xbrianlee can you rebase off my latest change for your test fix?

**Comment by xbrianlee** [comment]
Manually forwarded w/ test fixes
https://github.com/brianchandotcom/liferay-portal/pull/141286

**Pull request closed without merging**
