### PR TITLE
LPS-171364 - As a publication user, I would like to move a change to another publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin we added a new column to the publications changes view that will require us to update the tests.  can you resend this pr with your fixes

**Comment by david-truong** [comment]
fixed conflict

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @david-truong, I update the tests and resent it with test-fixes on https://github.com/liferay-publications/liferay-portal/pull/413, all of the tests look good now.

**Pull request closed without merging**
