### PR TITLE
LPS-178710

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-178710
https://issues.liferay.com/browse/LPS-181853

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@ctang3 @suilin when I tried to move a change... some of my changes disappeared.  They aren't in the old or new publication.

1. Create 2 publication
2. Edit the home page to change a fragment.
3. Move change to the other publication

Can someone take a look?

**Comment by suilin** [comment]
@david-truong @ctang3, I can reproduce the issue with the steps you provided and I verify it's not caused by current changes. I report the issue on [LPS-182489](https://issues.liferay.com/browse/LPS-182489), another issue for widget on [LPS-182490](https://issues.liferay.com/browse/LPS-182490). We will do more exploratroy testing for [LPS-171364](https://issues.liferay.com/browse/LPS-171364), and will update the issues that we found. Thanks.

cc @xbrianlee

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/528

**Pull request closed without merging**
