### PR TITLE
LPS-175931 - Added wiki page change displays when editing a wiki page within publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@suilin can you update the wiki test to match this?

**Comment by suilin** [comment]
@david-truong I updated the test and resent it on https://github.com/liferay-publications/liferay-portal/pull/429, can we forward it?

**Comment by david-truong** [comment]
Yes thank you!

**Pull request closed without merging**
