### PR TITLE
LPD-21520 Add workflow actions to the dropdown menu

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-21520](https://liferay.atlassian.net/browse/LPD-21520) and [LPD-22865](https://liferay.atlassian.net/browse/LPD-22865)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@gislayne-vitorino please check if the failures are related

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
@pei-jung Looks like some failures are related, I'll work on them

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
Update related to an issue in playwright test, still going to send a fix to poshi tests that are failing

**Comment by pei-jung** [comment]
Fixed poshi failures and merge conflict. See https://github.com/liferay-publications/liferay-portal/pull/1165

**Pull request closed without merging**
