### PR TITLE
LPD-18467 Ingore FragmentEntry columns with large data when conflict checking

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPD-18467

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Review by pei-jung — CHANGES_REQUESTED** [review]
@noornajj we don't modify the `*PersistenceImpl.java` directly. These classes are autogenerated by service builder. You'll need to add the `change-tracking-resolution-type` attribute to the columns in the service.xml and regen. And I believe we want to use `merge` for these columns instead of `ignore`.

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:publications

**Pull request closed without merging**
