### PR TITLE
LPS-176984 - Review changes is hiding changes that should not be hidden

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee can you help me verify these results

**Comment by xbrianlee** [comment]
@david-truong All of the test failures above are unrelated

**Comment by suilin** [comment]
@david-truong, as Brian's comment there are no issues related to current changes, and I also checked the fllowing issues:

- There is no Segment change showed up: The issue has been resolved and it need a test-fix based on the change, I resent on https://github.com/liferay-publications/liferay-portal/pull/444

- There is no Permission change showed up: I updated the specific permission on the ticket [LPS-176984](https://issues.liferay.com/browse/LPS-176984?focusedCommentId=2861498&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2861498), could you look at if the change is needed?

- Document Folder changes doesn't show up when uploading Files through Multiple Files Upload: The issue has been resolved.

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
can you resend your test fix on top of my latest change.  It should fix the permissions not showing issue.

**Comment by david-truong** [comment]
actually i'll just cherry pick it for you

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
