### PR TITLE
LPS-161315 - As a publication admin, I would like to define templates that users can use to create their publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@xbrianlee can you see why the publication templates test is failing

**Comment by xbrianlee** [comment]
Re-running tests in https://github.com/xbrianlee/liferay-portal/pull/1064 since this PR doesn't include all of the test changes from https://github.com/brianchandotcom/liferay-portal/pull/127756

**Comment by xbrianlee** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/127952

**Pull request closed without merging**
