### PR TITLE
LPS-187436 As a publication user, I would like to share my collection to anyone through an url

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@suilin I fixed the issue when accessing the share link. Can you verify?

**Known Issue: page preview is not working for the publication guest user when accessing via the share url.**

@david-truong I left out the changes for the preview because it's not working as expected. Depending on the layout type, it can check for the UPDATE permission when generating the page content. I didn't want to override the user or permission checker because that seem too hacky. I reached out to the echo team to see if there are other options for getting the page preview. I will work on a fix for the preview and send it separately.

**Comment by david-truong** [comment]
Sounds good lets just open a bug for it and fix it as a bug for the next sprint

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
Hi @pei-jung, the issue has been fixed with current pr, should we forward it?

**Comment by suilin** [comment]
Hi @pei-jung, I cherry-pick the functional tests with current commits on https://github.com/suilin/liferay-portal/pull/676, I found that it directs to default welcome page instead of 404 page if we access an expired Link, is it expected? I updated the steps as follows:

1. Set feature.flag.LPS-187436=true
2. Create a Publication
3. Review Publication
4. Click Share Access button 🔗 
5. Click Share Link tab
6. Enable “Allow anyone with the link to view this publication”
7. Copy URL
8. Disable “Allow anyone with the link to view this publication”
9. Sign out
10. Navigate to URL

Actual Result: It redirects to the welcome page.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@suilin I added a fix to redirect an expired/invalid link to the 404 page. This is ready to forward if there're no more issues. Thank you!

**Comment by suilin** [comment]
@pei-jung, all of issues have been fixed and I cherry-pick the new functional tests and sent on https://github.com/liferay-publications/liferay-portal/pull/718, but there is a conflict that must be resolved, can you look at it? Thanks.
```
Conflicting files
modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/servlet/taglib/ChangeTrackingIndicatorDynamicInclude.java
```

cc @xbrianlee

**Pull request closed without merging**
