### PR TITLE
LPS-186230 Migrate Publication History to use Dataset Display

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @xbrianlee, can you add functional test for this? Thank you!

Screen Shot 2023-06-20 at 6 04 04 PM

Screen Shot 2023-06-20 at 6 04 21 PM

**Comment by xbrianlee** [comment]
@pei-jung Sure! We'll add a new functional test soon in [LPS-188346](https://liferay.atlassian.net/browse/LPS-188346)

**Comment by pei-jung** [comment]
Added color styling to the status labels

Screen Shot 2023-06-21 at 1 48 00 PM

Screen Shot 2023-06-21 at 1 58 20 PM

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@pei-jung can you take care of the sf error?

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
i saw the error was some sort of timeout... rerunning to see if it fixed itself

**Comment by david-truong** [comment]
@pei-jung can you rebase and fix the conflict?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @pei-jung, I'm working on adding the new functional test, I found when I revert the published publication, it navigates to edit the publication page, can you look at it? Thank you!

Steps to reproduce:
1. Add property `feature.flag.LPS-180155=true`
2. Enable Publications
3. Add a new publication "P1"
4. Add some content
5. Publish "P1"
6. Navigate to the Publications History Tab
7. Revert "P1"

Result: The Edit page shows up instead of the revert page.
Revert P1

cc @xbrianlee

**Comment by david-truong** [comment]
resent with fixes: https://github.com/liferay-publications/liferay-portal/pull/623

**Pull request closed without merging**
