### PR TITLE
LPS-202192 Run scheduled jobs for journal articles and blog entries a…

### PR DESCRIPTION
**Pull request by noornajj**
…fter publishing a publication.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
@noornajj this looks the same as your last PR. Maybe you forgot to force push to your branch?

**Comment by noornajj** [comment]
Yeah I forgot to force push

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by allen-nagtalon** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
