### PR TITLE
LPS-159501 need to open up space to perform upgrade in 7.3.x

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@achaparro

**Comment by david-truong** [comment]
ci:test:upgrade

**Comment by xbrianlee** [comment]
ci:test:publications-environments

**Comment by xbrianlee** [comment]
ci:test:upgrade
 
 Re-running this test suite. The last run had lots of unrelated, unique failures making it difficult to discern related failures.

**Comment by brianchandotcom** [comment]
@xbrianlee @david-truong i merged this manually.

**Comment by xbrianlee** [comment]
ci:test:upgrade

**Pull request closed without merging**
