### PR TITLE
LPD-24820 Escaping the link causes the url to behave incorrectly

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-24820

### CODE REVIEW

**Comment by pei-jung** [comment]
Do we have test for this yet? If not, please add a test.

**Comment by brookedalton** [comment]
There is a test: https://testray.liferay.com/home/-/testray/case_results/2565062977

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
Manually forwarded due to rebase error: https://github.com/brianchandotcom/liferay-portal/pull/149944

**Pull request closed without merging**
