### PR TITLE
LPD-33336 Buffered increment runnable processing occurs in the same thread when not in production mode

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-33336
for https://liferay.atlassian.net/browse/LPP-55023

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
The fix is causing the `User` cell in the Review Changes screen to be empty. 

image

However, the user is present in the `Created By` row if you view that change. 

image

Maybe something with the FDS code is affected by the reverted commit?

**Comment by pei-jung** [comment]
Closed in favor of https://github.com/liferay-publications/liferay-portal/pull/1334

**Pull request closed without merging**
