### PR TITLE
LPS-148530

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@xbrianlee Please help me scan test results once it is finished.

Thanks.
Tina.

**Comment by xbrianlee** [comment]
@tinatian Could you take a look at the failure? It seems to be related to these changes.
```
     [exec] > Task :apps:change-tracking:change-tracking-service:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/change-tracking/change-tracking-service/src/main/java/com/liferay/change/tracking/internal/search/spi/model/query/contributor/CTModelPreFilterContributor.java:114: error: incompatible types: CTEntry cannot be converted to long
     [exec] 						className, ctEntry, excludeProductionModelClassPKs);
```
Console log: https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3586/consoleText

**Comment by tinatian** [comment]
ci:test:publications

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
@tinatian These tests results look good. Also I smoke tested the original bug and the appears to fix it.

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
