### PR TITLE
LPS-204124 Remove unused @Reference variables in ScheduledPublishMessageListener.java

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-204124](https://liferay.atlassian.net/browse/LPS-204124)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:forward

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:stable:norebase

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
