### PR TITLE
LPS-129369

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications-environments

**Comment by david-truong** [comment]
@xbrianlee @suilin can you please take a look at the test results?

**Comment by xbrianlee** [comment]
ci:test:publications-environments

Noticed the following error in `PublicationsConflict#AssertNoConflictForDeletionsCombinationPublications`. This doesn't seem to be reported in any ticket and this error hasn't happened in other recent test runs. Re-runing this test suite to verify if it's a fluke.
```
LIFERAY_ERROR: On after publish callback failure for change tracking collection 4 by com.liferay.change.tracking.store.internal.CTStoreCTEventListener@7b1a76b5
```

**Comment by suilin** [comment]
> ci:test:publications-environments
> 
> Noticed the following error in `PublicationsConflict#AssertNoConflictForDeletionsCombinationPublications`. This doesn't seem to be reported in any ticket and this error hasn't happened in other recent test runs. Re-runing this test suite to verify if it's a fluke.
> 
> ```
> LIFERAY_ERROR: On after publish callback failure for change tracking collection 4 by com.liferay.change.tracking.store.internal.CTStoreCTEventListener@7b1a76b5
> ```

The test has been passed on the second run, no new issues were found.

**Comment by suilin** [comment]
Hi @david-truong @ctang3, I found Publications#IsBrowserHistoryPreserved Weblogic environment only failed on this PR and https://github.com/liferay-publications/liferay-portal/pull/122 when execute curl command to get company, details on https://issues.liferay.com/browse/LPS-159290?focusedCommentId=2730888&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2730888, I didn't figure out why the two PR can cause the same issue, could you help to look at it? Thank you!

**Comment by xbrianlee** [comment]
We ended up determining that the test failure mentioned above happens upstream as well.

Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/121048.

**Pull request closed without merging**
