### PR TITLE
Lps 157814

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-157814

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by noornajj** [comment]
Resent https://github.com/liferay-publications/liferay-portal/pull/456

**Pull request closed without merging**
