### PR TITLE
LPS-172496 - Deleting a portlet with a modified configuration from a Publication incorrectly leads to a Deletion Modification Conflict

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:reevaluate:1397401_2434

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you help me review this one

**Comment by david-truong** [comment]
@qa-publications can someone please take a look

**Comment by david-truong** [comment]
rebased to fix conflict...

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@joshchong can you check the results?

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:reevaluate:1357401_3409

**Comment by joshchong** [comment]
hey @david-truong, i'm seeing some two things in this PR that is odd and isn't happening anywhere else:

**1) Modifying widget configurations while in a publication adds many changes to the publication.**

My steps:
- Add any widget to any page, for example the Asset Publisher on the home page
- Add a new publication
- While on the publication, edit and save any value within the configuration of the Asset Publisher
- Navigate to the Publications review page
- :x: Over 50 Portlet Preference Value items for the Asset Publisher are present from the one configuration change.
- This happens with other widgets as well. It also happens if adding the widget after creating the publication instead of before

**2) When upgrading a 7.4.x Portal database with an existing Publication to this branch, navigating to the Publication results in a "Review Changes is temporarily unavailable" error**

My steps:
- Upgrade a 7.4.x bundle to this branch
- You can use the following data dump which is what one of the failing tests use: [data-archive-publications-mysql.zip](https://github.com/liferay-publications/liferay-portal/files/10494618/data-archive-publications-mysql.zip)
- Start Portal and navigate to the existing Publication
- :x: The page is unavailable and "Review Changes is temporarily unavailable." appears. 
https://user-images.githubusercontent.com/14988026/214439009-e9b07fe8-d595-415b-b35f-db752590401d.mp4

**Comment by david-truong** [comment]
@joshchong

1. I investigated the code and this is the correct behavior.
2. I pushed up a fix for this.  Can you please retest?
3. @achaparro can you provide feedback?

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop going to try another approach and resend

**Pull request closed without merging**
