### PR TITLE
LPS-146573 As a publication user, I would like to always have my editors always be in a publication.

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@tinatian This is ready for review

FYI @xbrianlee

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:publications

**Comment by david-truong** [comment]
rebase and resent: https://github.com/liferay-publications/liferay-portal/pull/89

**Pull request closed without merging**
