### PR TITLE
LPS-185551 - Exceptions when adding multiple documents in a Publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by xbrianlee** [comment]
Test results above look good. `PublicationsDM#DeleteDMFolderWithMultipleFiles` also passes on Oracle and DB2.

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
@david-truong The test results look good. SF just needs to be fixed before we forward this.

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
