### PR TITLE
LPS-178009 - As a publication user, I would like to know all the changes that will be moved, when I move changes.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by noornajj** [comment]
Hi @david-truong 

Yeah, I'll test this out

**Comment by david-truong** [comment]
@noornajj you are going to update this one right?  I'm going to close this one

**Comment by noornajj** [comment]
@david-truong yeah, I'm going to update it. I'm waiting for LPS-194056 to be merged to liferay/master and rebase. 
I want to double check I get both changes working correctly together.

**Comment by noornajj** [comment]
@david-truong 
sent https://github.com/liferay-publications/liferay-portal/pull/698

**Pull request closed without merging**
