### PR TITLE
LPD-27966 Return jsonObject value

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-27966

Found by test: [LPD-23974 Comments link is added to workflow info display](https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/change-tracking-web/viewChangesWorkflow.spec.ts#L202)

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:relevant

**Review by ctang3 — APPROVED** [review]
Confirmed the fix on my local. 
image

Marking this as approved, thanks Brooke!

**Comment by ctang3** [comment]
ci:forward

**Pull request closed without merging**
