### PR TITLE
LPD-25833 Take ctCollectionId into account for Resource Permission upgrade

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-25833

### CODE REVIEW

**Comment by david-truong** [comment]
ci:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:report: 2571674953

**Comment by brookedalton** [comment]
ci:report:2571681688

**Comment by brookedalton** [comment]
ci:report:2571674953

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
