### PR TITLE
LPS-x Auto generated

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:reevaluate:1267401_3859

**Comment by xbrianlee** [comment]
ci:test:publications

Re-running this test suite since I'm getting different test results locally

**Comment by xbrianlee** [comment]
Need to wait for Diamond Bar ISP maintenance to re-run this

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
i:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
@david-truong There's a few issues here:
1. Unable to add a calendar to a page within a publication
2. Unable to add an attachment to a MB thread
3. [com.liferay.change.tracking.store.internal.test.CTStoreTest.testDeleteFile](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-
downstream(master)/104809//testReport/com.liferay.change.tracking.store.internal.test/CTStoreTest/testDeleteFile)

Can you look into these?

**Pull request closed without merging**
