### PR TITLE
LPS-193823 - Add Client Secret and Client Id as fields to CTRemote and ctRemoteId to CTCollection

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by suilin** [comment]
Hi @david-truong, 

- The publications remote server functional test needs to be updated, here is the commit that Brian worked before https://github.com/liferay/liferay-portal/commit/d609718f169143fb7e9394528f8850df3c7f6a64, can you cherry-pick it to current branch?
- All of the publications integration tests failed, due to `Execution failed for task ':apps:change-tracking:change-tracking-test:compileTestIntegrationJava`, can you look at it? Thank you!

cc @xbrianlee

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
Hi @david-truong, the issue I commented above has been fixed with the new commits, but there are still four integration tests failed, can you look at it? Thanks.

- com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest > testDeleteCTCollectionByExternalReferenceCode
```
     [exec] com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest > testDeleteCTCollectionByExternalReferenceCode FAILED
     [exec]     java.lang.UnsupportedOperationException: This method needs to be implemented
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testDeleteCTCollectionByExternalReferenceCode_addCTCollection(BaseCTCollectionResourceTestCase.java:464)
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testDeleteCTCollectionByExternalReferenceCode(BaseCTCollectionResourceTestCase.java:439)
```

-  com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest > testGetCTCollectionByExternalReferenceCode
```
     [exec]     java.lang.UnsupportedOperationException: This method needs to be implemented
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testGetCTCollectionByExternalReferenceCode_addCTCollection(BaseCTCollectionResourceTestCase.java:485)
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testGetCTCollectionByExternalReferenceCode(BaseCTCollectionResourceTestCase.java:471)
```

- com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest > testPatchCTCollectionByExternalReferenceCode
```
     [exec]     java.lang.UnsupportedOperationException: This method needs to be implemented
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testPatchCTCollectionByExternalReferenceCode_addCTCollection(BaseCTCollectionResourceTestCase.java:583)
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testPatchCTCollectionByExternalReferenceCode(BaseCTCollectionResourceTestCase.java:556)
```
- com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest > testPutCTCollectionByExternalReferenceCode
 ```
     [exec]     java.lang.UnsupportedOperationException: This method needs to be implemented
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testPutCTCollectionByExternalReferenceCode_addCTCollection(BaseCTCollectionResourceTestCase.java:641)
     [exec]     	at com.liferay.change.tracking.rest.resource.v1_0.test.BaseCTCollectionResourceTestCase.testPutCTCollectionByExternalReferenceCode(BaseCTCollectionResourceTestCase.java:590)
```

cc @xbrianlee

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
resent: https://github.com/liferay-publications/liferay-portal/pull/678

**Pull request closed without merging**
