### PR TITLE
LPS-176196 - As a publication admin, I would like to set a default template when creating a new publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee @suilin can one of you take a look at the results and forward if they are okay?

**Comment by suilin** [comment]
@david-truong, the failures are not related to this PR, I will forward it.
cc @xbrianlee

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
