### PR TITLE
Lps 182960 5 17

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@suilin Please prioritize the scanning of this pull once ci is finished.

Thanks.
Tina.

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
@tinatian, there are two unique failures for current changes:
1.com.liferay.commerce.product.change.tracking.test.CPDefinitionOptionRelTableReferenceDefinitionTest.testDiscardCTEntry
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.liferay.change.tracking.test.util.BaseTableReferenceDefinitionTestCase.testDiscardCTEntry(BaseTableReferenceDefinitionTestCase.java:99)
```

2. com.liferay.commerce.product.change.tracking.test.CPDefinitionOptionRelTableReferenceDefinitionTest.testDiscardCTEntry
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.fail(Assert.java:96)
	at com.liferay.change.tracking.service.test.CTCollectionServiceTest.testDiscardCTEntryWithRemovedParent(CTCollectionServiceTest.java:144)
```

**Comment by joshchong** [comment]
@tinatian @suilin from my local testing, I it looks like this PR is causing a regression where a conflict in a publication is not discarded properly if a web content article was deleted and published in another publication.

My steps:
1. In production, create a web content article "WC"
2. Create and checkout a publication P1
3. In P1, delete "WC" (move to recycle bin)
4. Create and checkout a publication P2
5. In P2, modify "WC" to "WC edit"
6. Publish P1 so that "WC" is moved to recycle bin in production
7. Attempt to publish P2. Observe there is a conflict
8. Discard the conflicting changes
9. Publish P2
10. While in production, navigate to web content admin
:x: **Actual result**: "WC edit" is present when nothing should be there
11. While in production, navigate to Recycle Bin
:x: **Actual result**: "WC edit" is present and "WC" is NOT present

**Comment by joshchong** [comment]
@suilin The regression I mentioned in my comment above seems to be related to the functional test failures. Specifically when `PublicationsConflict#ResolveDeletionModificationConflictPublicationsByDiscarding` is run, it is causing an issue where the web content admin is breaks and poshi is unable to delete the virtual instance that the test ran on bc of the following error:
```No JournalArticleResource exists with the primary key #####```
Because the virtual instance can't be deleted, new virtual instances in subsequent tests are unable to be created bc they can't create VIs with duplicate names. This leads to issues for all tests run after that one including issues with creating web content articles (which is why you see the `Cannot find structureId` error). See [example jenkins batch](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519635/) where all test after have failed. This is why there is a disparity between the tests that are failing on relevant and the publications suite, bc that one test runs with a different batch of tests for the two suites.

I believe this issue only occurs when actually running the poshi test `PublicationsConflict#ResolveDeletionModificationConflictPublicationsByDiscarding` as opposed to just following the steps manually. I think the reason for this is the test's use of JSON WS macros which results in different behavior compared to doing things manually. The most notable example is the test's use of `JSONWebcontent.deleteWebContent` while in a publication. That macro completely deletes the WC (deletes from database) instead of just moving it to the recycle bin. This is actually not a valid use case because in the UI a user is not able to completely delete a wc article while on a publication (delete is not a menu option in recycle bin and trash buttons are greyed out). We should update that test to move the wc article to recycle bin instead of deleting it.

**Comment by joshchong** [comment]
@suilin also, I believe you can remove the workarounds here: https://github.com/liferay/liferay-portal/blob/b73b0c42a4a6db100b868c15f8edb7697be39ae0/portal-web/test/functional/com/liferay/portalweb/tests/enduser/publications/PublicationsConflict.testcase#L546-L556

in my manual testing I didn't run into any issues executing the steps that were commented out.

**Comment by suilin** [comment]
@joshchong I see, thanks for your help and I'm going to update the test case that you mentioned.

**Comment by tinatian** [comment]
Resend at https://github.com/liferay-publications/liferay-portal/pull/569

**Pull request closed without merging**
