### PR TITLE
LPS-201100 - Can not move or discard change with more than 1000 entries on OracleDB

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee @suilin can you help me monitor the results for this one.  it is for a customer issue

**Comment by suilin** [comment]
The relevent failures are not related to current changes, publications and publications-db is pending. @xbrianlee, can you help to look at the suites after they completed, thanks.

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@david-truong The integration tests added in this PR are still [failing](https://testray.liferay.com/reports/production/logs/2023-11/test-1-39/test-portal-acceptance-pullrequest(master)/8286/modules-integration-oracle193-jdk8/0/2/com.liferay.change.tracking.internal.test.LargeDatasetCTTest.txt.gz?authuser=0). Are we planning to move forward with these changes despite these failures?

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
ci:test:publications-db

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
