### PR TITLE
LPD-22673 Add view usages link to workflow info display 

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-22673
https://liferay.atlassian.net/browse/LPD-22674

### CODE REVIEW

**Comment by brookedalton** [comment]
Not my SF failure, fix is in BChan's queue: https://github.com/brianchandotcom/liferay-portal/pull/149112/commits/5e927bf318ea49e17c1c49c92be9b83f9db0903a

**Comment by brookedalton** [comment]
https://github.com/liferay-publications/liferay-portal/assets/46908843/1882cf67-8b5c-4934-a266-dfe2bc1cc831

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
@brookedalton good job! Looks like Noor's PR got merged. Can you rebase and fix the merge conflict?

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@brookedalton is the playwright test in our publications suite?

**Comment by brookedalton** [comment]
@pei-jung yes, any test file added to the change-tracking-web test folder in playwright is added to the publications suite and since this test is part of the LPD-10703 epic I added it to the existing test file (viewChangesWorkflow.spec.ts)

**Comment by pei-jung** [comment]
@brookedalton got it. I know you have verified the test locally. Do you think we need to run it on ci to confirm again?

**Comment by brookedalton** [comment]
@pei-jung no I don't think so although there are new failures due to [LPD-22773](https://liferay.atlassian.net/browse/LPD-22773)

**Comment by pei-jung** [comment]
@brookedalton ok, can you or Noor work on updating the test? Thanks!

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
