### PR TITLE
LPS-173700 - Improve performance of CTSQLTransformerImpl

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:reevaluate:1397401_2530

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
@david-truong [This test failure](https://testray.liferay.com/home/-/testray/case_results/2173577725) is related to these changes. Could you take a look?

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@joshchong can you take a look at the results?

**Comment by joshchong** [comment]
@david-truong I'm going to have to rerun the relevant tests. A lot of failures look to be caused by network issues

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/129457

**Pull request closed without merging**
