### PR TITLE
LPS-197272 Create CTDisplayRenderer for AnnouncementsEntry

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPS-197272

@david-truong

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:bundle

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee can you check the results?

**Comment by xbrianlee** [comment]
ci:forward

Test results look good 👍

**Comment by xbrianlee** [comment]
ci:forward:force

Test results look good 👍

**Pull request closed without merging**
