### PR TITLE
LPS-196983 - As a publication admin, I would like to add the ability to add a remote from the toolbar

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@suilin @xbrianlee can you check the results?

**Comment by xbrianlee** [comment]
@david-truong Test results look good. Can this be forwarded?

**Comment by david-truong** [comment]
Yes thank you

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141527

**Pull request closed without merging**
