### PR TITLE
LPS-117633 make MailService CTAware

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you check the failures here

**Comment by xbrianlee** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/122728

**Pull request closed without merging**
