### PR TITLE
LPS-161035 - As a publication user, I would like to view the history of an asset across multiple publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@noornajj i've made my changes now.  the major changes i made was to simplify the service to a single call, I added a little more styling, added the missing permissions, and fixed the provider to initialize the service properly.  unfortunately i just squashed all the commits so you will need to manually compare with your branch.

**Comment by noornajj** [comment]
Hey @david-truong,

Yeah, I took a look at everything and it looks good. Thanks for fixing those up. 
The only comment I have is for the LPS identifiers in the commit messages. Did you want to change the ones that are journal related to LPS-161038?

**Comment by david-truong** [comment]
we can just link them in jira

**Comment by david-truong** [comment]
@xbrianlee do you think you can add a test for us?  I also wonder if we need to add a feature flag for this

**Comment by david-truong** [comment]
actually i added the feature flag so i ammended the message to have the correct lps ticket

**Comment by xbrianlee** [comment]
@david-truong Sure thing, I just created https://issues.liferay.com/browse/LPS-166697 for this. Is there a particular user flow we should focus on?

Regarding the FF: If the feature is incomplete without additional development or it's blocking new development, I would add a FF. If not, I would just test this carefully and push it to master.

**Comment by david-truong** [comment]
its complete without any extra dev.  it just adds a new tab that might be jarring so i added the feature flag

**Comment by david-truong** [comment]
@xbrianlee i'm going to forward it as is.  Can you add the ticket on a follow up pr?

**Comment by david-truong** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
