### PR TITLE
LPS-159501 clean up thumbnails and previews in publications that were not properly created

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by xbrianlee** [comment]
Manually tested using the steps in [LPS-159792](https://issues.liferay.com/browse/LPS-159792). Test results also look good.

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Missed a functional test failure ([PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/home/-/testray/case_results/1936879035?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1936875567%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc))
```
     [java] 2022-08-08 23:09:49.388 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.change.tracking.web
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.DLFileVersionPreview' doesn't exist
```
Console log: https://testray.liferay.com/reports/production/logs/2022-08/test-1-26/test-portal-acceptance-pullrequest(master)/4373/functional-upgrade-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0
Dump: [data-archive-portal-mysql.zip](https://github.com/liferay-publications/liferay-portal/files/9285625/data-archive-portal-mysql.zip)

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@xbrianlee can you review the tests?

**Comment by xbrianlee** [comment]
@david-truong All of the except for the same test. There's a new error this time.
```
[java] 2022-08-11 16:48:18.222 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.change.tracking.web
[java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.CTSContent' doesn't exist
```
Console log: https://testray.liferay.com/reports/production/logs/2022-08/test-1-33/test-portal-acceptance-pullrequest(master)/2105/functional-upgrade-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

Re-running this test suite to see if the failures are unique since I can't check test history. Testray is currently down.

**Comment by xbrianlee** [comment]
@david-truong These results look good. Can we forward this?

I wasn't able to add my test yet because I'm waiting for BChan to merge https://github.com/brianchandotcom/liferay-qa-portal-legacy-ee/pull/574 (pre-requisite).

**Comment by david-truong** [comment]
Yes let's forward and add the tests when we are ready

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
