### PR TITLE
LPS-129369 LayoutClassedModelUsage constraint violation conflict auto resolution

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by suilin** [comment]
Waiting for publications-environments results.

**Comment by xbrianlee** [comment]
Running more tests in https://github.com/xbrianlee/liferay-portal/pull/872

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/163

**Pull request closed without merging**
