### PR TITLE
LPS-142374 Unable to schedule Publications when using Safari and Firefox

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@xbrianlee This should be good to go, can you retest please? Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@tinatian This PR is ready for your review.
- All test failures are unrelated to these changes.
- We covered scheduling, rescheduling, and unscheduling Publications with functional tests, but we're unable to add coverage on Safari and Firefox due to these browsers not being supported on CI. We'll manually test these scenarios on occasion.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
