### PR TITLE
LPS-131088 Implement basic CTDisplayRenderer for Role

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-131088

### CODE REVIEW

**Comment by ctang3** [comment]
@noornajj  Looks great overall, nice work! Just needs those 2 minor changes and it's good to go. 

@xbrianlee at a quick glance the ci:test:publications failure looks like its from unstable/flaky tests - could you please confirm? Thanks!

**Comment by xbrianlee** [comment]
@ctang3 Yeah you're right. All of those failures are caused by bugs outside of Publications.

**Comment by ctang3** [comment]
@noornajj Are you able to see these? Not sure if I have to be assigned as a reviewer or something. 
image

**Comment by noornajj** [comment]
No, I can't see those reviews in the PR

**Comment by noornajj** [comment]
I'll make the updates and resend the PR then

**Comment by ctang3** [comment]
@noornajj you can do a force push in this case. Force push shouldn't be done if I'm in the actually in the process/middle of actively reviewing but I don't mind if you do it before I start, for future reference. 

I think I need to contact Kiyoshi or someone again to get rights for this repo. I got some invite to collab but it expired :x

**Comment by xbrianlee** [comment]
@ctang3 @noornajj I just added you guys as collaborators for this repo. You'll have to accept the email invite within a week.

**Comment by ctang3** [comment]
@tinatian This is ready for final review to `ci:forward`, thanks!

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by ctang3** [comment]
@noornajj  Could you re-run `formatSource` for the module again? Thanks!

**Comment by noornajj** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:forward

**Comment by ctang3** [comment]
@xbrianlee Doesn't look like these failures are related to the PR's code. Could you confirm? Much appreciated!

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Forwarded to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/116481

**Pull request closed without merging**
