### PR TITLE
LPS-161315 - As a publication admin, I would like to define templates that users can use to create their publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@qa-publications can you check the results?

**Comment by david-truong** [comment]
@joshchong can you check the results?

**Comment by brianchandotcom** [comment]
@david-truong @joshchong there was a rebase error in 3038f17e

@david-truong I also made a ton of tiny changes in my origin. Please review.

Merged to master.

**Comment by xbrianlee** [comment]
`relevant` and `publications` test results look good overall. I'm forwarding a small test fix for the Publications template test we added in this PR - https://github.com/xbrianlee/liferay-portal/pull/1102. We'll monitor for regressions once these changes and BChan's changes make it upstream.

**Pull request closed without merging**
