### PR TITLE
LPS-154710 use osgi configuration to enable publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
Running tests in https://github.com/liferay-publications/liferay-portal/pull/108

**Pull request closed without merging**
