### PR TITLE
LPS-183191 Documents Folder and Permission Changes shows up when browsing Publishing Import

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-183191](https://liferay.atlassian.net/browse/LPS-183191)

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin can you check to see if the failures have been fixed?

**Comment by suilin** [comment]
@david-truong, the issue has been fixed, and the failures are not related to current changes, should we forward it?

/cc @xbrianlee

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
