### PR TITLE
LPS-199203 Content page does not support locales in review changes

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPS-199203

I believe this bug ticket is partly user error for the steps described in the ticket, but I did find an actual bug related to this where the locale selection dropdown wasn't working correctly - the user was unable to change the locale of the preview render when reviewing a Layout change that has multiple localization versions. 

It looked like the steps in this ticket needed to add two steps for the localization to be created, and therefore displayed in the localization dropdown: 
- "publish the page" after editing each localized version of the page, so "publish the page" should be added after step 3a
- Go to Site Builder > Pages > Click options ... button > Click translate > Select zh-CN > Click Publish

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@ctang3 see my changes: https://github.com/liferay-publications/liferay-portal/pull/842

**Pull request closed without merging**
