### PR TITLE
Lps 179035

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
@david-truong

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@david-truong [Semver for change-tracking-rest-client](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766897/testReport/junit/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_change_tracking_change_tracking_rest_client_/) needs to be fixed, but other than that it's ready to be forwarded

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by david-truong** [comment]
resent with fixes: https://github.com/liferay-publications/liferay-portal/pull/728

**Pull request closed without merging**
