### PR TITLE
LPD-23430 Add workflow transition actions to the dropdown menu

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
Update for: https://liferay.atlassian.net/browse/LPD-23430

The successMessages are not appearing in the modals(when accepting transition actions) due to [this parameter in the request](https://github.com/liferay-publications/liferay-portal/blob/3b0e769bf9693a2727dfb13fa574630259df06d6/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/portlet/action/GetEntryRenderDataMVCResourceCommand.java#L1086-L1087), if removed they appear back again.
Right now the place they are being shown are on the My Workflow Tasks page, even with the parameter on
image

The workflow transition tasks and its functions do appear in the dropdown now
image
image

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@gislayne-vitorino are we required to keep this parameter?

**Comment by gislayne-vitorino** [comment]
@david-truong we are not, if we fix this behavior the parameter can be removed. Right now it is only masking this issue

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/1248

**Pull request closed without merging**
