### PR TITLE
LPS-195949 | Enable change tracking for Bookmarks 

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-195949

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Review by pei-jung — APPROVED** [review]
LGTM! Well done, @brookedalton! 👍

**Comment by pei-jung** [comment]
Hi @david-truong, can you take a look at this to see if anything is missing?

**Comment by david-truong** [comment]
@brookedalton you probably need to  change-tracking-resolution-type="merge" to some of the fields to reduce the number of conflicts customers will run into.  can you take a look at [blogs/blogs-service/service.xml](https://github.com/liferay/liferay-portal/blob/2160c2a1d32282f4d191782b9fac19e4bd1db845/modules/apps/blogs/blogs-service/service.xml#L26)

**Comment by pei-jung** [comment]
Hi @david-truong can you provide more details on the `change-tracking-resolution-type` attribute? The service builder doc just says that this is used when resolving columns during conflict, but it's not clear what it actually does. When do we use it? and what does each resolution type mean?

**Comment by david-truong** [comment]
There are different types but the most common one is merge.  They are used during conflict checking during the auto resolution phase.  Merge just means overwrite the result without worrying about it. Last update wins.

**Comment by pei-jung** [comment]
Got it. Do we usually apply this attribute to the workflow fields? I see a couple being added to the `statusDate` field but not the `status` or `statusByUser*` fields. Is that the norm?

**Comment by david-truong** [comment]
we've been applying them as customers run into issues... we really need to have tests to attempt to replicate the issues for all services so that we can apply it on a consistent basis.

**Comment by pei-jung** [comment]
Oh ok. So I guess we leave out the workflow ones until there's an issue? Here are the fields I think should should have the attribute applied. Do they look good to you?

**BookmarksEntry**
modifiedDate, folderId, treePath, name, url, description, priority, lastPublishedDate

**BookmarksFolder**
folderId, modifiedDate, parentFolderId, treePath, name, description, lastPublishedDate

**Comment by david-truong** [comment]
You won't need to add it for folderId.  You will never have a conflict on folderId.  I think modifiedDate also will never have a conflict as they are handled in a specific way.  In general I would stick to the fields that a user can directly or indirectly manipulate

**Comment by pei-jung** [comment]
@david-truong ok, we can leave out the `modifiedDate` field. I included `folderId` because you can move a BookmarksEntry/BookmarksFolder to a different folder, so conflicts might happen.

**Comment by david-truong** [comment]
That would only be for bookmarksentry right?

**Comment by david-truong** [comment]
For bookmarksfolder it would only be parentforlderid

**Comment by pei-jung** [comment]
Right, only parentFolderId for BookmarksFolder and folderId for BookmarksEntry.

**Comment by pei-jung** [comment]
Here is the final list

**BookmarksEntry**
folderId, treePath, name, url, description, priority, lastPublishedDate

**BookmarksFolder**
parentFolderId, treePath, name, description, lastPublishedDate

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
