### PR TITLE
LPS-185856 - Allow change tracking framework to use finder cache

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by xbrianlee** [comment]
@david-truong I can put something to test this scenario. Would the data in the site initializer be enough? For other tickets in this epic, we tested at the scale of thousands of assets.

**Comment by david-truong** [comment]
create as much as you need to be able to tell if theres a good performance benefit

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:stable

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:stable

**Comment by xbrianlee** [comment]
ci:forward:force

Failures above are unrelated

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/137226

**Pull request closed without merging**
