### PR TITLE
LPS-193854 - Add Service Account and OAuth2 Application for Remote Publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee do you know how we need to pass this SF error?  I am using the same license for all the files next to it.

**Comment by xbrianlee** [comment]
@david-truong The year in the file is wrong
```
- * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
+ * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
```

**Pull request closed without merging**
