### PR TITLE
LPS-187183 Experience selector

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPS-187183

@david-truong

### CODE REVIEW

**Comment by xbrianlee** [comment]
@ctang3 Can you look into this regression?

Test steps:
1. Enable Publications
2. Create a document
3. Add a Publication - P1
4. Rename the document
5. Add a Publication - P2
6. Rename the document to something else
7. Attempt to publish P2
8. Checkpoint: there is a conflict that needs to be resolved
9. View conflicting change details
image

Poshi report: https://testray.liferay.com/reports/production/logs/2023-09/test-1-40/test-portal-acceptance-pullrequest(master)/5957/functional-tomcat90-mysql57-jdk8/1/14/LocalFile.PublicationsDM_ResolveConflictingPublicationsByDiscarding/index.html.gz?authuser=0

**Comment by xbrianlee** [comment]
FYI I added a test fix in https://github.com/xbrianlee/liferay-portal/pull/1308 and I'm currently going through the remaining test failures. They mostly seem to be caused by the issue I described above.

**Comment by ctang3** [comment]
@xbrianlee Pushed a fix and also rebased onto latest master

**Comment by xbrianlee** [comment]
Latest test results look good! Just waiting on @david-truong's review to forward.

**Comment by david-truong** [comment]
taking a look now

**Comment by david-truong** [comment]
@ctang3 can you fix these issues:

- if i modify an experience in a publication it ends up listing it twice
- when I modify a page for a given experience in a publication, the preview just shows the default experience

**Comment by ctang3** [comment]
See PR #704

**Pull request closed without merging**
