### PR TITLE
LPS-176351 - Can not review changes in a page when publication is published or out of date.

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin we had to also update the requirements of this one.  Can we update this test also?  We actually want to be able to browse published and if possible out of date publications... with the caveat that out of date publications should fail gracefully if it doesn't work.

**Comment by suilin** [comment]
@david-truong, I'm not very clear about the requirements and I'd like to confirm with you about the expected reuslts, for the published publications we can review the changes; but for the out of date publications, we cannot review changes any more?

**Comment by david-truong** [comment]
@suilin don't worry about testing for out of date publications.  let's just fix the test for published publications

**Comment by suilin** [comment]
@david-truong, sorry, I'm still not clear about the issue, now both with or without the fixes, the result are the same: We can review the changes when clicking on the Published publications, what's the expected result after the fixes?
Before

**Comment by david-truong** [comment]
1. Create a publication
2. Edit a page
3. Review Changes
4. View the side by side changes of Page

**Comment by xbrianlee** [comment]
@david-truong I'm not sure what the difference is with what's upstream. I tried your steps above and also tried publishing and then viewing the side by side changes of the page, but I see no difference. Can you point out what we're supposed to assert here? 

Upstream
Upstream

PR
PR

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
This is what it is supposed to show:
Screen Shot 2023-03-06 at 9 46 33 PM

**Comment by xbrianlee** [comment]
@david-truong Test results look good, however I did notice [one new test failure](https://testray.liferay.com/home/-/testray/case_results/2222755366). It looks like an error state isn't caught gracefully.

Test steps:
1. Add a Web Content Article
2. Enable and add a Publication
3. Add a new page - Test Page Name
4. Add a Web Content Display widget on this page
5. Select Web Content Article
6. Publish Publication
7. Get the CTCollectionId of the publication
8. Open localhost:8080/web/guest/test-page-name?previewCTCollectionId=${ctCollectionId}

Expected: https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/365/functional-jboss73-mysql57-jdk8/0/5/LocalFile.Publications_CannotPreviewPublishedPublicationViaURL/screenshots/after0.jpg.gz?authuser=4

Actual: https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9581/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.Publications_CannotPreviewPublishedPublicationViaURL/screenshots/before2.jpg.gz?authuser=4
```[beanshell] 2023-03-07 04:34:15.606 ERROR [http-nio-8080-exec-3][BasePersistenceImpl:643] Caught unexpected exception
[beanshell] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.exception.PortalException: Change tracking collection {"mvccVersion": 2, "ctCollectionId": 1, "companyId": 47608, "userId": 47640, "createDate": "Tue Mar 07 04:33:25 GMT 2023", "modifiedDate": "Tue Mar 07 04:34:11 GMT 2023", "schemaVersionId": 1, "name": "Publication Name", "description": "", "status": 0, "statusByUserId": 47640, "statusDate": "Tue Mar 07 04:34:11 GMT 2023"} is read only```

**Comment by david-truong** [comment]
@xbrianlee it may have been a temporary error.  I've rebased and errors appear as expected.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
@david-truong The error I described previously is still happening in the latest run. Can you give it another look?
>[LocalFile.Publications#CannotPreviewPublishedPublicationViaURL](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403735//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Publications_CannotPreviewPublishedPublicationViaURL_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-03/test-1-29/test-portal-acceptance-pullrequest(master)/6726/functional-tomcat90-mysql57-jdk8/1/6/LocalFile.Publications_CannotPreviewPublishedPublicationViaURL/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-03/test-1-29/test-portal-acceptance-pullrequest(master)/6726/functional-tomcat90-mysql57-jdk8/1/6/LocalFile.Publications_CannotPreviewPublishedPublicationViaURL/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-03/test-1-29/test-portal-acceptance-pullrequest(master)/6726/functional-tomcat90-mysql57-jdk8/1/6/jenkins-console.txt.gz)

**Comment by david-truong** [comment]
Wait this one is supposed to fail now.  This is what we changed.

**Comment by david-truong** [comment]
@suilin can you send a pr to delete that test or test the opposite?

**Comment by suilin** [comment]
Hi @david-truong, after the new change, [Publications#CannotPreviewPublishedPublicationViaURL](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403735//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Publications_CannotPreviewPublishedPublicationViaURL_) when previewing the published publication via URL, _An unexpected system error occured_ message throws in the page and the following error throws 
```
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.exception.PortalException: Change tracking collection {"mvccVersion": 2, "ctCollectionId": 1, "companyId": 20096, "userId": 20123, "createDate": "Tue Mar 21 04:07:13 GMT 2023", "modifiedDate": "Tue Mar 21 04:07:51 GMT 2023", "schemaVersionId": 1, "name": "Publication Name", "description": "", "status": 0, "statusByUserId": 20123, "statusDate": "Tue Mar 21 04:07:51 GMT 2023"} is read only
	at com.liferay.change.tracking.internal.CTPersistenceHelperImpl.isInsert(CTPersistenceHelperImpl.java:81) ~[?:?]
```
 
As I understand the expected result should we can preview the published publication via URL, please let me know I misunderstand it, thanks.

**Comment by david-truong** [comment]
@suilin can you give me the steps to reproduce?  Not everything will be able to be previewed via the url parameter though depending on the way the entity was published.

**Comment by xbrianlee** [comment]
@david-truong I listed the steps in [this comment](https://github.com/liferay-publications/liferay-portal/pull/427#issuecomment-1458596915). For reference, [LPS-158789](https://issues.liferay.com/browse/LPS-158789) is the related story ticket for this test.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @david-truong, the failure is related to this change, do we need to forward it?

**Comment by david-truong** [comment]
I'm spending more time thinking about the solution since you and Brian had confusion over this ticket... for sure the customers are also going to get confused

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
