### PR TITLE
LPS 164752 - allow KB Article to be sent to Publication + Workflow 

### PR DESCRIPTION
**Pull request by Vy-CES**
Hi Team, 

This is a change request for https://issues.liferay.com/browse/LPS-164752. According to @david-truong, I need to allow the KB article to be sent through workflow and publication instead of making it dismissed from the transaction.

## Motivation
This P/R is relied on the previous work done for wiki here: https://github.com/liferay-publications/liferay-portal/pull/374

Please review it and let me know your feedback,

Thanks
Vy

### CODE REVIEW

**Comment by david-truong** [comment]
@Vy-CES great!  I will review it this week

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@Vy-CES see my changes here: https://github.com/liferay-publications/liferay-portal/pull/458

**Pull request closed without merging**
