### PR TITLE
LPS-186455 Create headless endpoints for CTEntries

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @xbrianlee, these failures don't look related to me. Can you confirm? Thanks!

**Comment by david-truong** [comment]
ci:test:stable

**Comment by xbrianlee** [comment]
ci:test:publications-as

**Comment by xbrianlee** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
ci:forward:force

**Comment by suilin** [comment]
@pei-jung, @david-truong, the failures for `publications`, `relevant`, `publications-db`, and `publications-as` suites are not related to current changes, I forward it.

cc @xbrianlee

**Pull request closed without merging**
