### PR TITLE
LPS-200858 - Cannot view related ctEntry details from the review page

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you help me check the results?

**Comment by xbrianlee** [comment]
The failures aren't related. This is ready to be forwarded 👍

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
