### PR TITLE
LPD-15297 New API to get CTCollection by class

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-15297

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@ctang3 looks like something is broken on BChan's origin. Can you rebase your changes to upstream master instead if your changes don't contain conflicts with BChan's origin?

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
@pei-jung  Rebased onto upstream master

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@ctang3 please fix the compile error.
```
     [exec] Execution failed for task ':apps:change-tracking:change-tracking-rest-impl:compileJava'.
```

**Comment by ctang3** [comment]
@pei-jung fixed

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:report:2536682634

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
