### PR TITLE
LPD-19615 - Empty publication can be scheduled or published after resolving conflicts

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-19615](https://liferay.atlassian.net/browse/LPD-19615)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Review by ctang3 — APPROVED** [review]
Validated functionality on my local 
image

Code changes look good to me. @pei-jung do you mind taking a quick 2nd look over the code as well? 

Should there also be a new test case in CTProcessLocalServiceTest to assert that the empty publication can't be published after resolving conflicts, like in the ticket steps?

**Comment by pei-jung** [comment]
> Should there also be a new test case in CTProcessLocalServiceTest to assert that the empty publication can't be published after resolving conflicts, like in the ticket steps?

Gi added a playwright test for it in [4336f58](https://github.com/liferay-publications/liferay-portal/pull/1253/commits/4336f582aab8f6171f6b01ac7ebefd179d61e8d3) so we don't need another test.

**Comment by pei-jung** [comment]
ci:report:19628746

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:report:23205843

**Comment by gislayne-vitorino** [comment]
The failures are not related

**Comment by gislayne-vitorino** [comment]
ci:forward

**Pull request closed without merging**
