### PR TITLE
LPD-30058 Optimize PublicationsConflict#AssertModificationConflictDisplays by removing unnecessary steps 

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-30058

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
Screen Shot 2024-07-01 at 9 27 15 PM

**Review by pei-jung — APPROVED** [review]

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
