### PR TITLE
LPS-179172 Rename Pages to Page Set to avoid confusion

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-179172](https://issues.liferay.com/browse/LPS-179172), [LPS-179031](https://issues.liferay.com/browse/LPS-179031)

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee can you help us take a look at this pr?

**Comment by xbrianlee** [comment]
ci:forward:force

`publications` and `relevant` results look good.

**Pull request closed without merging**
