### PR TITLE
LPS-200161 Allow CTEntries to be filtered and sorted by status

### PR DESCRIPTION
**Pull request by pei-jung**
Screen Shot 2023-10-30 at 2 37 58 PM

Screen Shot 2023-10-30 at 2 38 53 PM

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@xbrianlee is this okay to forward?

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
