### PR TITLE
LPS-180928 Hide Dynamic Data Mapping Structure changes

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-180928](https://issues.liferay.com/browse/LPS-180928), story: [LPS-179029](https://issues.liferay.com/browse/LPS-179029)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
resent: https://github.com/liferay-publications/liferay-portal/pull/501

**Pull request closed without merging**
