### PR TITLE
LPS-159649 Workflow UI

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-159649

Added: 
- New status column with workflow status of the underlying entity behind the CTEntry
- Labels for workflow statuses, extracted into a react component
- Sorting of workflow status column. Always shows items with a workflow status before those without (non-workflow entities) if sorting by workflow status column. 
- Disables the `Publish` confirmation button on the Conflict View page and shows a warning/alert box message on the 'Conflicts View/Confirm Publish' page if there are unapproved changes
- Unapproved changes check runs before conflict check. Doesn't run conflict checking code if there are unapproved changes.
- Uses memoization based on the CTEntry's `modelClassNameId` to improve performance of unapproved changes checking

@david-truong

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 can you split the service changes along with the buildService into its own commit and the UI changes in a different commit and finally the buildLang last

**Comment by david-truong** [comment]
@xbrianlee @suilin can someone help update the tests for this PR

**Comment by ctang3** [comment]
@xbrianlee @suilin FYI I'll be rebasing and rearranging the commits, so give it 30 mins or so and I'll tag you guys in another comment once that has been completed.

**Comment by ctang3** [comment]
@xbrianlee @suilin @david-truong Rebased and force pushed cleaned up commits

**Comment by xbrianlee** [comment]
@ctang3 As an update, all of the points you mentioned in the description of this PR passed manual testing and I'm wrapping up the automated regression testing in https://github.com/liferay-publications/liferay-portal/pull/205.

One question: Is approving an asset entry within a publication in scope for this ticket or even a valid use case? Currently the workflow approver can see the pending asset entry while in the publication, however the user doesn't get a notification and nothing shows up in the user's workflow tasks.

**Comment by ctang3** [comment]
@xbrianlee Looks like the lack of notification is due to UserNotificationEvent not being change tracked or CTAware ([LPS-157477](https://issues.liferay.com/browse/LPS-157477)). I'll take a look into it and see which solution would fit, and add that fix to this PR.

**Comment by ctang3** [comment]
@xbrianlee Pushed a commit that should fix the issue you mentioned, tested following ([LPS-157477](https://issues.liferay.com/browse/LPS-157477)). Could you recheck this please? Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
@ctang3 Much better! I was able to get through the user flow in [LPS-161039](https://issues.liferay.com/browse/LPS-161039) without running into errors.

I did find one other issue however. Asset entries approved within a workflow won't list a user in the Publications changes table.
WithWorkflow

Without workflow enabled, the correct user will show up in the Publications changes table.
WithoutWorkflow

Could you take a look at this?

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/250

**Pull request closed without merging**
