### PR TITLE
LPS-198312 Add beta indicator to beta features

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@david-truong 

Move Changes
Screen Shot 2023-10-05 at 2 41 25 PM
Screen Shot 2023-10-05 at 2 42 27 PM

On-demand user
Screen Shot 2023-10-05 at 3 02 16 PM
Screen Shot 2023-10-05 at 3 02 04 PM

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
