### PR TITLE
LPS-161037 - As a publication user, I would like to view changes to a page across multiple publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin can you help us update LocalFile.PublicationsWebContent#CanViewWebContentTimelineOverMultiplePublications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by suilin** [comment]
Hi @david-truong, I'm working on updaing `PublicationsWebContent#CanViewWebContentTimelineOverMultiplePublications`, but I didn't find the Timeline in Publications bar, I have added the property to `feature.flag.LPS-161033=true` portal-ext.properties, could you help to look at it? Thank you!

cc @xbrianlee 

Publications Bar

**Comment by david-truong** [comment]
Edit the change and it will be in the publication bar

**Comment by david-truong** [comment]
@suilin i found an issue trying to create a screenshot for you.  will resend later

**Pull request closed without merging**
