### PR TITLE
LPD-15347 - GET request used for editing a publication comment

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@pei-jung do you know if this is the right way to check the CSRF token?

**Comment by david-truong** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
looks right to me

**Comment by pei-jung** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
