### PR TITLE
LPS-197281 - The explanation should appear when moving changes failed between publications with conflicts

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin this is a fix for [LPS-197281](https://liferay.atlassian.net/browse/LPS-197281), [LPS-197292](https://liferay.atlassian.net/browse/LPS-197292), and [LPS-182679](https://liferay.atlassian.net/browse/LPS-182679)

@ctang3

**Comment by david-truong** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:bundle

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
Hi @david-truong, I verified that [LPS-197281](https://liferay.atlassian.net/browse/LPS-197281) was fixed, but for [LPS-197292](https://liferay.atlassian.net/browse/LPS-197292) and [LPS-182679](https://liferay.atlassian.net/browse/LPS-182679) both of them move to another failed and throw message `Error:One or more changes conflict with existing changes in the destination publication`, can you look at it? Thanks.

**Comment by david-truong** [comment]
That is the expected behavior.  You are trying to move something with missing dependencies.  The site or the structure needs to move first.

**Comment by suilin** [comment]
@david-truong, I see, but it's a little confusing since it misses the dependencies not have conflicts, do you think this is necessary to implement a new method for the situation?

cc @xbrianlee

**Comment by xbrianlee** [comment]
@david-truong What Linda's describing sounds like a possible UX improvement. Should consider it out of scope for this ticket?

**Comment by xbrianlee** [comment]
The test results here look good otherwise

**Comment by david-truong** [comment]
Yeah let's send what we have now and add a new ticket to improve the message for future

**Comment by david-truong** [comment]
@xbrianlee can you forward

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141506

**Pull request closed without merging**
