### PR TITLE
LPS-118546 - Fail to add a page template with Widget Page Template within Publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you review this one for me?

**Comment by xbrianlee** [comment]
ci:test:echo

`publications` and `relevant` results above look good

**Comment by xbrianlee** [comment]
Failures in the `echo` run do not appear to be related to these changes
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2204188952&testrayRunIdA=2204104851&statusB=2

**Comment by xbrianlee** [comment]
@david-truong Can this be forwarded?

**Comment by david-truong** [comment]
Yes please

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
