### PR TITLE
LPS-199501 The change title changed to type plus ID after deleting with dataset display

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee are the failures related?

**Comment by xbrianlee** [comment]
The failures aren't related. This is ready to be forwarded 👍

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
