### PR TITLE
LPS-158879 can not invite user to join publication if the user already has publication role

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee @suilin this should fix all those InviteUser errors... I always thought tests were flaky... but when I checked it out there were certain cases where it would fail.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
Hi @david-truong, thanks for fixing on the issue, I found the issue is caused by LPS-148661. Now it is fixed by your pr and the failures are not related to the pr, can we forward it?

**Comment by david-truong** [comment]
Sure

**Comment by david-truong** [comment]
I would consider this a blocker

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
