### PR TITLE
Lps 179035

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPS-179035

There are a couple bugs that need to be fixed:

1. Not all models are returning group info. I have already created https://liferay.atlassian.net/browse/LPS-193793 and Pei said she'll look into it.
2. The entries are not being sorted correctly based on the type name because there is an issue with localized values being reindexed

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj can you fix the sf error?

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@noornajj can you resend once all bugs are fixed.  It will not be beneficial to merge this beforehand.

**Pull request closed without merging**
