### PR TITLE
LPS-187436 As a publication user, I would like to share my collection through an url

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@xbrianlee I rebased and resolved the conflicts.

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141522

**Pull request closed without merging**
