### PR TITLE
LPD-28734 Add and implement handling of hideDefaultSuccessMessage parameter in CompleteTaskMVCActionCommand

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-28734

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Review by pei-jung — COMMENTED** [review]
@ctang3 please add a test.

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
@pei-jung the added test is ready for review, thanks!

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
