### PR TITLE
LPD-20756 generate data pages 

### PR DESCRIPTION
**Pull request by ctang3**
Not sure if this would be for [LPD-20756](https://liferay.atlassian.net/browse/LPD-20756) or [LPD-20838](https://liferay.atlassian.net/browse/LPD-20838).

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@ctang3 i don't see the CTEntries being created.  Will that be created automatically?

**Comment by ctang3** [comment]
@david-truong No we have create every entity type manually. Good catch, I forgot about needing to add code to create manually linked CTEntries. I'll add it then push a fix.

**Comment by david-truong** [comment]
Sounds good. Also the default numbers seems a bit low.  Can you take a look at the spreadsheet and set the defaults from that

**Comment by ctang3** [comment]
I could but from what I understood from Pei - we'd eventually write something like SampleSQLBuilderTest where we override benchmark.properties values and run that as needed that to generate the .sql file that'll be used in the actual benchmark tests, which are in the [liferay-benchmarks-ee](https://github.com/liferay/liferay-benchmark-ee/tree/master/grinder/liferay-benchmark/src/main/java/com/liferay/benchmark/script) repo. 

Since SampleSQLBuilderTest appears to be only checking that it generates a valid sql file instead of generating large quantities, it seems troublesome down the line to have to constantly edit that test to override a high default number for each CT entity we add support for in DataFactory. 

I did add benchmark.properties overrides to SampleSQLBuilderTest in this PR, but for future PRs I was thinking of just not adding more overrides to the test and making the defaults sanity check amounts. Thoughts on this?

**Comment by david-truong** [comment]
Ahh ok that makes sense

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
@david-truong Updated my branch with the CTEntry creation

**Comment by david-truong** [comment]
@ctang3 looks good now.  have you been able to test it with a running portal?

**Comment by david-truong** [comment]
@pei-jung should i forward this one?

**Comment by pei-jung** [comment]
New PR: https://github.com/liferay-publications/liferay-portal/pull/1167

**Pull request closed without merging**
