### PR TITLE
LPS-117637 - Can not delete a role within a publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@suilin can you take a look at these results?

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
@david-truong, the failures are not related to current changes, should we forward it?

cc @xbrianlee

**Comment by david-truong** [comment]
ci:forward:force

**Comment by suilin** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/136063

**Pull request closed without merging**
