### PR TITLE
LPS-161619 Enable CT for phone numbers

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-161619

@david-truong

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 i think those test failures are related to your PR

**Comment by ctang3** [comment]
@david-truong  Looking into this now

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
Updated branch. Gislayne is working on Address, so I just added a skeleton TRD for it.

**Comment by david-truong** [comment]
@ctang3 i think you need to run baseline on portal-kernel

**Comment by ctang3** [comment]
ci:reevaluate:1397401_4415

**Comment by ctang3** [comment]
@david-truong Going to close this PR and pick Gislayne's commits that implement CT for Address into this branch since Phone Numbers depends on Address. Need to make some fixes to her AddressTableReferenceDefinition then I'll resend the combined PR.

**Comment by ctang3** [comment]
Please see https://github.com/liferay-publications/liferay-portal/pull/524

**Pull request closed without merging**
