### PR TITLE
LPS-205652 Remove countries from publications unsupported application list

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-205652

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by brookedalton** [comment]
Failures unrelated

**Comment by brookedalton** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
