### PR TITLE
LPS-197713 Create Test for JournalContentSearch TableReferenceDefinition

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-197713](https://liferay.atlassian.net/browse/LPS-197713)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@xbrianlee is this ok to forward?

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/142218

**Pull request closed without merging**
