### PR TITLE
LPD-33486 User remains logged into Intercom session after logging out of Liferay

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33486

# How am I fixing it?

The cookies created by Intercom to track a user's sessions are being deleted via a logout hook.

The difficult aspect of how this module is implemented is that everything depends on a page load to trigger the Javascript from the various providers. This may not happen for instance if `Guest Users Allowed` is disabled. The fix opts to remove the cookies rather than via [Intercom('shutdown')|https://www.intercom.com/help/en/articles/16845-how-do-i-end-a-session] due to these challenges.

If there are any ideas as to how to trigger the Javascript only when a user has logged out please let me know.

# How can you verify that it works?

From `modules/apps/click-to-chat/click-to-chat-test` run `gw testIntegration --tests *.LogoutPreActionTest`

Manual steps can be found on LPD-33486 but will require an Intercom account.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@david-truong @mrjohn1911 Would either or both of you mind reviewing these changes? If you'd like to test locally let me know and I can provide the Intercom details.

**Comment by david-truong** [comment]
@jonathanmccann do you plan on using those constants in other places other than the LogoutPreAction?  If not, I think you should keep it private within LogoutPreAction instead

**Comment by jonathanmccann** [comment]
@david-truong Thanks for catching that, I've updated the usage.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@jonathanmccann you can forward whenever you are ready

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
