### PR TITLE
LPS-159649 - As a publication user, I would like to see the workflow status of entities when reviewing changes

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by joshchong** [comment]
ci:test:publications-environments

**Comment by joshchong** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by suilin** [comment]
@david-truong, I'm analyzing the results, but I'm confused about the latest two commits that added the notification `Select production to review the change.`, when we are in the publication mode. Does it mean we need to select on production, if it is how can we review the Publications changes? Thanks!

@joshchong, I finished analyzing the publications-environments and relevant suites, there are no related issues were found.

**Comment by david-truong** [comment]
There are 4 scenarios we need to test - for:
- a workflow created in production while viewing the notification in production. Everything should function as expected.
- a workflow created in a publication while viewing the notification in the same publication. Everything should function as expected.
- a workflow created in production while viewing the notification in a publication. You will get the message "Please select production to review this change." The notification link will not go anywhere.
- a workflow created in a publication but viewed from another publication or production.  You will get the message "Please select the publication $publicationName to review the change." The link will not go anywhere.

**Comment by suilin** [comment]
Send the pr with the new functional test on https://github.com/brianchandotcom/liferay-portal/pull/123146.

**Pull request closed without merging**
