### PR TITLE
LPD-24104 Refactor the display of workflow info to use a react component

### PR DESCRIPTION
**Pull request by noornajj**
The view changed a bit in terms of styling. The table has a border whereas before it did not. 
Is this ok or do we want to keep the same styling?

Screenshot from 2024-04-26 09-31-40

### CODE REVIEW

**Comment by noornajj** [comment]
Border has been removed

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
