### PR TITLE
LPD-19510 - Publishing a publication that is in queue does not show status correctly

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@pei-jung can you take a quick look and see if I might be missing any other locations where this might need a change?

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
