### PR TITLE
LPS-182238 - Implement change tracking for Address

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:reevaluate:1287401_6505

**Comment by david-truong** [comment]
@xbrianlee @suilin can one of you check the results?

**Comment by xbrianlee** [comment]
ci:test:um

**Comment by xbrianlee** [comment]
ci:test:publications-as

**Comment by xbrianlee** [comment]
publications-db

**Comment by suilin** [comment]
publications-db

**Comment by suilin** [comment]
ci:test:publications-db

**Comment by suilin** [comment]
@david-truong, @xbrianlee I finished analyzing the results of `Publications`, `relevant`, and `publications-as` and publications-db` suites, there are no issues related to the current change. Should we forward it?

**Comment by david-truong** [comment]
Please forward if testing is good

**Pull request closed without merging**
