### PR TITLE
LPS-161037 - As a publication user, I would like to view changes to a page across multiple publications

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
@suilin can you update the timeline test now?  You should be able to see the history for webcontent now.

**Comment by david-truong** [comment]
@xbrianlee can you check the results for relevant?

**Comment by xbrianlee** [comment]
Will do, I'll also update `PublicationsWebContent#CanViewWebContentTimelineOverMultiplePublications` since Linda is out this week

**Comment by xbrianlee** [comment]
ci:test:echo

`relevant` results look fine. Since we're making changes to the journal module, I'm going to run the `echo` suite.

**Comment by david-truong** [comment]
@xbrianlee i rebased to latest and updated the dropdown menu

**Comment by xbrianlee** [comment]
Continued in https://github.com/liferay-publications/liferay-portal/pull/495

**Pull request closed without merging**
