### PR TITLE
LPS-133973 Create Tests for Social TableReferenceDefinitions

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-133973

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
