### PR TITLE
LPS-198236 Create test for DDMStorageLinkTableReferenceDefinition

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-198236](https://liferay.atlassian.net/browse/LPS-198236)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
@gislayne-vitorino i saw one minor change: https://github.com/liferay-publications/liferay-portal/pull/794

**Comment by david-truong** [comment]
ci:stop

**Pull request closed without merging**
