### PR TITLE
LPS-161618 - As a publication user, I would like to track changes to email addresses

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
Sorry it took so long to review

@moltam89 I had to drop [de83960](https://github.com/liferay-publications/liferay-portal/pull/320/commits/de8396041c9a99c1464a5cdadc5a6352a2e95236) and [f2af30d](https://github.com/liferay-publications/liferay-portal/pull/320/commits/f2af30d1f2973e4ed55a23f428c0d71904d68f8f) to get change-tracking-test to pass its tests.

Can you investigate why those tests are failing if your assumptions are true?

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee can you help us check the results?

**Comment by suilin** [comment]
@david-truong, the results look good, none of the failures are releated to the current changtes.

cc @xbrianlee

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin can you double check the results again.  I had to rebase to fix the versioning conflicts.

**Comment by david-truong** [comment]
ci:reevaluate:1387401_5020

**Comment by david-truong** [comment]
@xbrianlee can you help check this one?

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/127085

**Pull request closed without merging**
