### PR TITLE
LPS-179035 - Render Publication Changes with Data Set Display

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@xbrianlee @suilin can you review this one?

**Comment by xbrianlee** [comment]
@david-truong Several tests in `com.liferay.change.tracking.rest.resource.v1_0.test.CTEntryResourceTest` failed. Could you take a look?
https://testray.liferay.com/home/-/testray/case_results/2430065606

The other test results look good.

**Comment by noornajj** [comment]
@david-truong 

The changes look good to me

**Comment by david-truong** [comment]
@noornajj is going to fix the test and make one final change to help with performance.

**Pull request closed without merging**
