### PR TITLE
LPS-133973 Create Tests for Social TableReferenceDefinitions

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee should I re-trigger the publications test suite?

**Comment by xbrianlee** [comment]
ci:test:publications

It looks like everything in the last run just timed out

**Comment by xbrianlee** [comment]
@pei-jung Are these test failures related at all? These failures haven't ever happened before, but it could be a fluke.
- [com.liferay.knowledge.base.change.tracking.test.KBTemplateTableReferenceDefinitionTest](https://testray.liferay.com/home/-/testray/case_results/2451885701)
- [com.liferay.knowledge.base.change.tracking.test.KBCommentTableReferenceDefinitionTest](https://testray.liferay.com/home/-/testray/case_results/2451885685)

The other results look fine.

**Comment by pei-jung** [comment]
@brookedalton can you help look into the test failures that Brian mentioned?

**Comment by brookedalton** [comment]
Resent with test fix: https://github.com/liferay-publications/liferay-portal/pull/758

**Pull request closed without merging**
