### PR TITLE
LPD-28802 Send email notification to user invited to a publication 

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-28802

### CODE REVIEW

**Comment by brookedalton** [comment]
Hi @pei-jung, 
BChan also asked me to make some name changes for the template and configuration file to follow similar conventions:
`email_change_tracking_collection_invitation_*`

- portal-impl/src/com/liferay/portlet/documentlibrary/dependencies/email_file_entry_added_subject.tmpl
- modules/apps/knowledge-base/knowledge-base-api/src/main/resources/com/liferay/knowledge/base/dependencies/email_kb_suggestion_resolved_subject.tmpl

`CTCollectionEmailConfiguration.java`
- AccountEntryEmailConfiguration.java

Let me know if these look ok or if I should change anything else

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
The test passed locally, will look into why it failed in CI 
Screenshot 2024-08-07 at 12 15 12 PM

**Comment by brookedalton** [comment]
ci:test:playwright

**Comment by brookedalton** [comment]
ci:test:playwright

**Comment by pyoo47** [comment]
ci:test:playwright

**Comment by brookedalton** [comment]
Test passed in CI:
https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/977500/testReport/change-tracking-web_ctCollectionEmailConfiguration.spec/

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:report:56011016

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
