### PR TITLE
LPS-138706 - Fail to publish the publication with deletion folder when the document deleted on production

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 can you take a look at my changes and see if this is okay?

**Comment by david-truong** [comment]
@suilin @ctang3 the failure to publish was fixed in a previous ticket: [LPS-187233](https://liferay.atlassian.net/browse/LPS-187233).  this is really just about fixing the conflict and dealing with the exception now.

**Comment by ctang3** [comment]
@david-truong I see, thanks for bringing that ticket to my attention! Your PR modification looks functionally the same. 

My only concern is that using your fetch may swallow true exceptions in cases where the CTSContent is null due to another type of bug, compared to a SQL query with safe guards to only let a null CTSContent through if it also fulfills certain conditions:

1. There is a CTEntry with a `deleted` change type for the CTSContent that belongs to a CTCollection other than the one currently being published
2. The CTEntry from `1.` belongs to a CTCollection that has already been published

I'm wary that if some bug causes CTSContent to be unexpectedly missing, it could be difficult to detect if true exceptions get swallowed due to the leniency of a fetch basically letting all conditions through. I wasn't around when these older lower levels of the change tracking project were being built like you were, so if you're confident that it won't be an issue after [LPS-187233](https://liferay.atlassian.net/browse/LPS-187233), then the fix looks good to me and would have better performance!

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by suilin** [comment]
Hi @david-truong, I analyzed the results, and the failures are not related to the changes. 
- I also checked [LPS-138706](https://liferay.atlassian.net/browse/LPS-138706) it has been fixed. 
- But for [LPS-138989](https://liferay.atlassian.net/browse/LPS-138989) it failed to publish due to `Modification Conflict: The conflict cannot be automatically resolved.` When I clicked on "Edit in P2", the error message shows up when navigating to Message Board. 
P2

It is caused by the following error, do you think we should fix it in the current PR? Thanks.
- Enable Publications
- Add a new DM folder with a DM file inside
- Add new publication "P1"
- Move the DM File to recycle bin
- Add a new publication "P2"
- Move the DM Folder with the DM file to recycle bin
- Publish "P2"
- Select "P1"
- Navigate to Document and Media
Result: The DM Folder is gone even though I only move DM File to recycle bin

cc @ctang3 @xbrianlee

**Comment by david-truong** [comment]
@suilin lets keep the tickets separate

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
