### PR TITLE
LPS-184787 Create headless endpoints for publications

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
Hi @xbrianlee, are the failures related?

**Comment by xbrianlee** [comment]
@pei-jung The only test failure that's related is [com.liferay.change.tracking.rest.resource.v1_0.test.PublicationResourceTest](https://testray.liferay.com/home/-/testray/case_results/2320748171)

**Comment by xbrianlee** [comment]
ci:test:publications-db

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@pei-jung can you fix the rest builder error?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
