### PR TITLE
LPS-193588 - PortletPreferences should declare PortletPreferenceValue as a child

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:reevaluate:1317401_9118

**Comment by david-truong** [comment]
@xbrianlee are these failures related?

**Comment by xbrianlee** [comment]
@david-truong These results look good to me

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
