### PR TITLE
LPS-200457 Invited user cannot see the publications on the onging tab

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
