### PR TITLE
LPS-198133 Create test for DDMStructureVersionTableReferenceDefinition

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for:  [LPS-198133](https://liferay.atlassian.net/browse/LPS-198133)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]
ci:forward

**Comment by pei-jung** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
