### PR TITLE
Lps 179035

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
@david-truong

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
Hey @david-truong 

These failures are related to [LPS-193793](https://liferay.atlassian.net/browse/LPS-193793)
Since the group info is not being returned, then the validation is failing because the groupId is 0

**Comment by david-truong** [comment]
@noornajj see my changes here: https://github.com/liferay-publications/liferay-portal/pull/707

**Pull request closed without merging**
