### PR TITLE
LPS-184787 Create headless endpoints for publications

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@xbrianlee is this safe to forward?

**Comment by xbrianlee** [comment]
@pei-jung The semver issue for change-tracking-api appears to be related. Can you take a look?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
