### PR TITLE
LPS-204131-LPS-204132 Remove unused @Reference variables in ViewScheduledMVCRenderCommand.java

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-204131](https://liferay.atlassian.net/browse/LPS-204131), [LPS-204132](https://liferay.atlassian.net/browse/LPS-204132)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward:force

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
