### PR TITLE
LPS-183191 - Documents Folder and Permission Changes shows up when browsing Publishing Import

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@xbrianlee are these failures related?

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by suilin** [comment]
@david-truong @gislayne-vitorino, there is a regression bug related to the current change, can you look at it? The steps are following:
1. Enable Publications
2. Add a new site "Site Name 1"
3. Add a new structure with fields "Numeric", "Text", "Image"
4. Add a new template according to the new structure
5. Add a new web content folder
6. Export the lar `publications-web-content-files.lar`
7. Add a new site "Site Name 2"
8. Add a new publication "Publication Name"
9. Navigate to web content and import `publications-web-content-files.lar`

Result: Fail to import the lar and CTEventException throws.
```
2023-05-25 00:17:42.663 ERROR [liferay/background_task-7][CTServiceRegistry:132] On after publish callback failure for change tracking collection 14 by com.liferay.change.tracking.store.internal.CTStoreCTEventListener@15f20f7e
com.liferay.change.tracking.spi.exception.CTEventException: com.liferay.change.tracking.store.exception.NoSuchContentException: No CTSContent exists with the primary key 61891
	at com.liferay.change.tracking.store.internal.CTStoreCTEventListener.onAfterPublish(CTStoreCTEventListener.java:95) ~[?:?]
	at com.liferay.change.tracking.internal.CTServiceRegistry.onAfterPublish(CTServiceRegistry.java:129) [bundleFile:?]
	at com.liferay.change.tracking.internal.background.task.CTPublishBackgroundTaskExecutor.execute(CTPublishBackgroundTaskExecutor.java:222) [bundleFile:?]
```

cc @xbrianlee

**Comment by david-truong** [comment]
hi linda how do yuo get an exception to show up?  the process fails but I don't get any exception. 
Capture-2023-05-25-014940

**Comment by suilin** [comment]
@david-truong, I retest it there is no error anymore, sorry for that, I will update the comment above.

**Pull request closed without merging**
