### PR TITLE
LPS-201333 LPS-201410 Update Sites and Types filter to exclude values from hidden changes

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
