### PR TITLE
LPS-198227 Create test for DDMDataProviderInstanceLinkTableReferenceDefinition

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for:[ LPS-198227](https://liferay.atlassian.net/browse/LPS-198227)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Review by david-truong — APPROVED** [review]

**Comment by david-truong** [comment]
ci:stop

**Comment by david-truong** [comment]
@gislayne-vitorino saw one small change: https://github.com/liferay-publications/liferay-portal/pull/789

**Pull request closed without merging**
