### PR TITLE
LPD-25347 Asset upgrade process does not take into account ctCollectionId when upgrading

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:echo

**Comment by gislayne-vitorino** [comment]
ci:test:upgrade

**Comment by david-truong** [comment]
@gislayne-vitorino can you rebase off master?

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:echo

**Comment by gislayne-vitorino** [comment]
ci:test:upgrade

**Comment by david-truong** [comment]
@gislayne-vitorino you need to update the test after rebasing

**Pull request closed without merging**
