### PR TITLE
LPS-153993

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin can you take a look at this error?

**Comment by suilin** [comment]
Hi @david-truong, the error is not related to the change, it's dm issue [LPS-154675](https://issues.liferay.com/browse/LPS-154675) and it has been fixed on upstream.

**Pull request closed without merging**
