### PR TITLE
LPS-187436 As a publication user, I would like to share my collection to anyone through an url

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
Updated button with link icon to open the Share Access modal
Screen Shot 2023-09-07 at 4 21 51 PM

Share Link tab with toggle and link
Screen Shot 2023-09-07 at 4 22 08 PM
Screen Shot 2023-09-07 at 4 22 00 PM

Access the share link as guest
Screen Shot 2023-09-07 at 4 18 18 PM
Screen Shot 2023-09-07 at 4 20 17 PM

Access an expired share link
Screen Shot 2023-09-07 at 4 18 56 PM

**Comment by xbrianlee** [comment]
@pei-jung These changes break adding a Publications template. I was able to verify it locally. Can you take a look at this issue?
image

**Comment by pei-jung** [comment]
Fixed NPE when adding publication template and force-pushed.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
Fixed the bug where the guest user should be logged out when navigated away from the publications portlet.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee @suilin forced push a couple changes

1. Guest user should not be included in the publication's collaborator list.
2. Added a new Sharing icon to the toolbar. Clicking on the icon will open the Share Access modal with the Share Link tab selected as default.
Screen Shot 2023-09-13 at 5 47 31 PM
Screen Shot 2023-09-13 at 5 47 59 PM

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@pei-jung i will be reviewing the ticket today now that the icon is in

**Comment by david-truong** [comment]
@pei-jung can we make the shared url friendlier?

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by Songyuewen** [comment]
Hi @pei-jung ,
I found a issue during working on [LPS-195715](https://liferay.atlassian.net/browse/LPS-195715). 
- Copy the share link and log out
- Access to the URL as guest user

Result: the URL direct to 'Terms of Use'. 
Expected result: Publications changes show up

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
Rebased and force pushed with the following changes:

- Share URL is shortened to `http://localhost:8080/o/change_tracking/review_changes?ticketKey=06dce6f4-7a03-8dd6-02fa-3af9273ea5fb`

- Fixed page preview in publications.  
@david-truong I was running into the same page preview issues with other users that have access to publications. This is due to the user missing the required permissions for the group and/or layout. To fix it, I added an [action command](https://github.com/liferay-publications/liferay-portal/pull/684/commits/3fab660b9f579d3add76c2b749107866a5f66bdb) that utilizes the `GetPagePreviewStrutsAction` to  generate the page preview as html and write it directly to the response. That way we can avoid unnecessary permission checks to load the page preview. If this looks good to you, I think we can get rid of the `CTCollectionPreviewFilter`.

- Fixed the issue where the guest user is redirected to the terms of use page when accessing the share link. cc @Songyuewen

**Comment by suilin** [comment]
ci:test:bundle

**Comment by david-truong** [comment]
@pei-jung if we expose that page like that would that mean if someone knew that URL they could view any page they wanted?

**Comment by suilin** [comment]
@pei-jung, I verified the issue that @Songyuewen brought up, now when a guest user accesses the shared link, it directs to the page `Password Recovery Question and Answer`, after I type it, it will redirect to the user login page with `Error:Your request failed to complete.` Can you look at it? Thanks.

I uploaded the video on https://github.com/liferay-publications/liferay-portal/assets/4927160/c10d2d64-3bfe-457e-b534-4bea98a18fb8.

**Comment by pei-jung** [comment]
@david-truong The preview url requires a valid auth token to work, so it will not work if you share the link to someone else. And for logged in user, they can manipulate the url and view any page they want. I think we can try these to fix it.

1. Obscure the url so it's hard to guess. We can encrypt the `ctCollectionId` and `plid` params so they display something like this `rHYwDSY4R74X0zaUYI%2BXSg%3D%3D` in the url.
2. Restrict preview to the modified pages in publication only if the user doesn't have the required VIEW permission. So that the user doesn't have access to other pages in production. This also means that there will be no split view in the preview if user has no view permission.

What do you think?

**Comment by david-truong** [comment]
@pei-jung ok i am reviewing the changes

**Comment by david-truong** [comment]
see my changes here: https://github.com/liferay-publications/liferay-portal/pull/708

**Pull request closed without merging**
