### PR TITLE
LPS-194056 Do not show the move changes URL for system changes

### PR DESCRIPTION
**Pull request by noornajj**

### CODE REVIEW

**Comment by noornajj** [comment]
@david-truong 
No it doesn't. This would actually need to be merged first so I can adjust the action URL for move changes in the dropdown actions for the new view.

**Comment by noornajj** [comment]
Actually, it doesn't matter which gets merged first but I would need to change the URL for whichever PR gets merges second.

**Comment by david-truong** [comment]
ok i'll send this one first since it's smaller

**Comment by david-truong** [comment]
see my changes here: https://github.com/liferay-publications/liferay-portal/pull/690

**Pull request closed without merging**
