### PR TITLE
LPS-164716 - Import LARs not working on a Publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @david-truong ,
I have found 2 issues with Enabling Export/Import for non Prod Publications:
1. Not all Staged Models are CTAware, any such Model present in a LAR will result in the original CT transaction validation failure.
2. I found that if LARs are used for both Prod and a Pub, the Pub likely won't be Publishable. I've used these steps for an an initial test:
```
# Enable Publications
# Create Site1
# Create a Web Content
# Create version 1.1 for the Web Content
# Export the Site to "v1.1.lar"
# Create version 1.2 for the Web Content
# Export the Site to "v1.2.lar"
# Create version 1.3 for the Web Content
# Export the Site to "v1.3.lar"
# Create Site2
# Create new Publications1
# Work on Publications1
# Import v1.1.lar
# Switch to Prod
# Import v1.2.lar
# Switch to Publications1
# Import v1.3.lar
# Review Publication changes

*Expected behaviour:* Review changes only shows version 1.3 change for the Web Content
*Actual behaviour:* Review changes shows all versions of the Web Content

Try to Publish Publications1

*Expected behaviour:* Publishing is successful
*Actual behaviour:* Publishing is unsuccessful
```

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:reevaluate:1337401_2795

**Comment by david-truong** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129692

**Pull request closed without merging**
