### PR TITLE
LPS-198109 Deleted documents are displayed as modified in review changes

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
@xbrianlee are the failures related?

**Comment by xbrianlee** [comment]
@pei-jung The semver failures for the following modules are unique:
1. [change-tracking-api](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/369307/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_change_tracking_change_tracking_api_)
2. [change-tracking-service](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/369307/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_change_tracking_change_tracking_service_)

The other results look good 👍

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
