### PR TITLE
LPS-187009 - Can not publish a publication when there is a duplicate mapping conflict in a mapping table

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj

**Comment by david-truong** [comment]
@xbrianlee @suilin can you test if i broke anything with my change?  This is related to anything that might generate a row in the Relationship table

**Comment by suilin** [comment]
@david-truong, the results look good, no tests are affected by the changes. And I don't find any changes in the Relationship table. Is it expected?
relationship

cc @xbrianlee

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
