### PR TITLE
LPS-157465 allow change tracked entities to skip publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@suilin would you be able to check the remaining errors for this pull

**Comment by suilin** [comment]
Hi @david-truong, there is no error related to the changes, but there is a test-fix after you changed `Publications Setting` to `Setting` in Instance settings, I'm going to fix it later, thanks.

**Comment by suilin** [comment]
Hi @david-truong, I'm also adding a new functional test to cover the change, but I found it doesn't work, could you help to look at what's wrong about my steps? Thank you!
* Enable Publications
* Navigate to System Settings > Publications 
* Type `com.liferay.blogs.service.impl.BlogsEntryServiceImpl ` in Production Only Models
* Add a new publication
* Add a new blog
* Change work on production
Result: There is no blog on production mode.

**Comment by suilin** [comment]
Hi @david-truong, I'm also adding a new functional test to cover the change, but I found it doesn't work, could you help to look at what's wrong about my steps? Thank you!
* Enable Publications
* Navigate to System Settings > Publications 
* Type `com.liferay.blogs.service.impl.BlogsEntryServiceImpl ` in Production Only Models
* Add a new publication
* Add a new blog
* Change work on production
Result: There is no blog on production mode.

**Comment by david-truong** [comment]
I used the model class name... But I'm open to making it the service name instead.  I just realized that the way I did it will fail on deletes I think.

Can we have the test check for updates and deletes also

**Comment by suilin** [comment]
Hi @david-truong, I tried to update and delete, it works for updaing, but as you mentioned it fails to delete. And I'm also doing the exploratory test. Will you fix it in this pr?

**Comment by suilin** [comment]
Hi @david-truong I resent it with the functional test(add, update, delete) to https://github.com/liferay-publications/liferay-portal/pull/132.

**Comment by david-truong** [comment]
https://github.com/liferay-publications/liferay-portal/pull/132

**Pull request closed without merging**
